#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib '../files/lib';
use Base::Page qw(page story);

page( 'code' => sub { story(*DATA) });

__DATA__
It was Christmas Eve, and Betty was ready for it. Her house was completely decorated with lights inside and out. The tree sparkled with the ornaments and tinsel. She had a few bags packed with gifts she was taking to her office to leave for her work friends. She had her Christmas music collection playing from her computer's speakers. She checked the caroling schedule and noticed that she didn't have a lot of time to get the gifts distributed at the office.
She took the bags out to her car along with a couple of canteens of warm apple cider. It wasn't that cold out that Christmas Eve night; but with the weather always waiting until after New Years to get nasty, she was used to not having white Christmases. It wasn't that late in the evening, but the roads were unusually empty. She saw only a few other cars on her way back into work.
"Maybe this year they got all of their shopping done early or online." she said out loud to herself.
She was able to park in a visitor's spot when she got to her building because the office was closed for the holidays. She hummed the carols that she would be singing that night with her church choir in town while swiping her access card to get in the front door. When she was inside, she couldn't help but break out into actual song. She stopped for a moment when she saw that the security desk wasn't manned. She sighed somewhat sadly when she remembered a memo going out to the employees that there would be layoffs, but those weren't going to happen until after the new year. She looked inside her bags for an untagged generic gift she could leave for the officers that had to work that night. She placed the two little green and red boxes on the security desk and pushed the button on the elevator.
She got to her office in a few minutes. It was a little chilly in the building because the company usually turned all the thermostats back to 50 degrees before the holidays to save on the electric bills. This year it seemed that they may have turned the heat off completely. She then realized that the lights had been turned off in the parking lot too. She shook off these off occurrences as she distributed little token gifts to all the cubicles in the room. Mostly she bought pens and post-its, but she always added her own little flourish to the gifts so that the recipients would always get a little smile whenever they used the mundane items she bought them. Taking as little time as possible, she got back to the elevator and through the still empty lobby. She looked at the monitors again. The guards must be doing rounds where there were no cameras she thought.
Getting back into her car, she started to hum again as she drove to her church. That Christmas Eve evening was so quiet. She listened to the mp3 player that she kept her Christmas music on during her drive. This was the holiday she loved most, even though she usually spent Christmas alone after church services were over. She never expected to get invited over to a fellow church member's house, though she went when offered with plenty of offerings to her hosts. She shook her head with mirth as she thought about how quiet the streets were around town.
When she got to the church, no one was there. After checking her watch, she called the pastor to find out if she had been late. The voice mail recording came through the speaker of her wireless headset, so she left a message and waited in her car for a few moments. Each year the choir had been getting smaller and smaller as was the congregation. There were only five people left to sing. Being able to sing tenor helped keep the songs balanced. She was the only single person in the choir without any children. The other four had familial obligations, which she understood completely.
After waiting for half an hour and getting her pastor's voice mail over and over, she decided to go caroling alone if no one else was coming. She caroled every year, and this one would not be an exception. Instead of singing the tenor chords that year, she would sing in her normal alto voice. She got out of her car and reached back in for her canteens of apple cider. When she got them out, she put them over her both her shoulders crosswise so they wouldn't slip off. She didn't need the songbook to sing the carols that they normally sang, but she took the book with her as a prop. There was only a slight chill in the air, so she just wrapped her large Christmas scarf around her neck and shoulders to keep her throat warm then started off into the neighborhood.
She sang corner to corner throughout the town. During most of her stops, no one came out to greet her. She looked around to see darkness coming from most of the windows. She couldn't think of what was making this year to different that people would go to bed this early on a Christmas Eve. There were a few who came out to sing a song or two with her, but those that did cried through them with such sadness that Betty was beginning to wonder what was going on to make everyone so sad this Christmas. A few of them thanked her for her bravery then went back inside their unseasonably dark homes. Since she was alone that Christmas, she decided to add a few more blocks to her caroling route.
When she got back to her car, she was really beginning to worry. Something was wrong since her pastor hadn't called her back. She left another voice mail then drove home. The drive was even more eerie than it was when she was going to her office. Looking at her watch, it was only 9:00 p.m. She got inside and put her mp3 player into the slot on her computer to continue to listen to Christmas music. She had collected days worth. She went into the kitchen to make sure the cookies she baked over the last week were ready to go tomorrow for the local food kitchen. She put a cup of water into the microwave for a cup of tea while she checked to see if the pastor had left her any messages at home.
Betty was going to break with her normal tradition of not watching, reading, or listening to the news during the holidays. She just thought that the media was too depressing to make the holidays happy. She sat on her sofa and reached out for the remote.
hr
In the newsroom of the local affiliate station, Nichole was getting ready for her first time behind the desk and in front of the camera. This morning she got the sudden promotion from production assistant to anchor. The rest of the anchors had families at home who needed them there. She was single and alone this Christmas Eve. Only two hours earlier, everyone with families left the station to go home. That left only five people there to maintain the broadcasts. It was time to cut in with the breaking news that night.
Just two hours earlier, the remaining staff at the station decided to have a bit of an orgy in the office of the affiliate's president. He had left the door unlocked, so they went in there to have some very comfortable fun. They didn't care who or what they were touching, they just wanted to feel something before that news broadcast began.
Mike, Danny, Jim, Maggie, and Nichole set up the feed to begin the broadcast.
hr
As Betty turned on the television there was a horrible wrenching. The ground shook beneath her feet. In just a moment, her house went dark for the first time on Christmas Eve when Nichole was about to broadcast the line "It appears that the Earth is going to get coal in its collective stocking this year." Nichole didn't get to say and Betty didn't get to hear those words uttered when a meteor destroyed the planet.
