#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib '../../../files/lib';
use Base::Page qw(page story);

page( 'heading' => 'Aleena, the Overpower of Afa and Afma', 'code' => sub { story(*DATA) });

__DATA__
I<This was written by a person I know only as Thraymire not by me. I have regretfully lost touch with him. I made a few additions to his story which will be in blue. I met Thraymire in a group I created on Excite.com when they had groups. The group was called AD&amp;D&#8482; for Adults (Afa). I was pretty lenient on how people should act in the group, but some of the users began to get on my nerves to the point I nearly deleted the group. I was persuaded to leave it alone and just monitored it without posting anything. I spun off a new group called AD&amp;D&#8482; for Mature Adults (Afma) with a select group from Afa. Both groups have been gone for a very long time, but had this story and wanted to share with you how another person viewed me at the time.>
hr
From the nothingness SPAN<that encompassed an area of space|^blue text^> came the Goddess. The Goddess, unhappy with her loneliness, SPAN<sought a power equal to her own. She found Ao of Toril. She saw what he had done and decided to|^blue text^> create for herself a world, and name it Afa. The Goddess then declared that a world without caregivers is but a shell, and she created powers breathing into each a quality unknown to even her that they may surprise and delight her with their actions. The powers selected forms as each one willed, and, as any siblings, selfishly fought each other and staked claim to ideals, thoughts, and created natural forces that each may have rulership over. The powers created clouds that made rain, making oceans. The powers made the land shake and move and created mountains. The powers then tried to imitate the Goddess and made for themselves creations to worship and adore them, but these were lifeless hulks. The powers tried countless numbers of forms and shapes, colors, differing designs and fashions; but each were lifeless, for the powers had not the essence to give their creations life as The Goddess had.
The powers beseeched the Goddess for the boon of creating life out of will. The Goddess saw how distressed her children were that they had no worshipers of their own, and came to a decision; She would not award her children the ability to create life, but instead breathed life into all their creations, and awarded to those creations the ability to create new life from within themselves, that they may multiply. The Goddess also endowed her children's creations with the unknown essence, that they may surprise and delight all with their freedom to choose. The Goddess then charged her children: 
"You have desired worshipers. You now have them, but also now must care for your creations. I award you authority over the eternal essence that each one has, but restrict you from force with these creations. You must earn their worship through favor shown to them. Each of these creations will live and die on Afa, but after death, I will allow the essence only those faithful to you to keep you company in the hereafter, so be diligent, encourage and assist your creations, that you will not be lonely yourselves"
And so, each creation was given knowledge a little at a time, and the powers vied for their worship. Rituals and traditions were started and carried on. Each power set down their own rules for the created, based on the ideals they claimed in their own past. But they were amazed, for the Goddess did not restrict each creation of the powers to only worship the power that created it, but gave each the ability to choose which rules they desired! The powers walked on Afa often, delighting in amazing their creations with their powers, and manipulating them into all manner of acts and war, but fearing the result if they warred on each other directly. 
So time marched on, with the different creations on the world of Afa expanding and warring on another, as do all children. The powers encouraged this play, and delighted in their positions as masters, but each of them desired to own more than their siblings, as children do.
From without Afa came a mortal messenger, a worshipper of a power alien and unknown to the creations, the powers, and the Goddess. The ideas of this interloper struck a cord with many on the surface of Afa, and caused much strife among the creations. The resultant war escalated to such levels as to cause the powers themselves to openly war in Afa, bickering and assaulting each other, as each tried to take what the other had, again, as children.
But the world of Afa could not take the tremendous strife. Continents were torn asunder, weather patterns changed, magic went awry, much was the suffering, and many were the deaths. This attracted the ire of the Goddess. Stepping down from her observation, the Goddess caused all warfare to take pause, and closed off Afa from all view from without. "What is best for Afa, comes from Afa", she declared, "Never again will interlopers cause strife on the first of my creations". 
To her bickering children, the Goddess announced, "Long have I watched, and been ashamed at you, my children. Strong is my anger toward you. For you each were given much freedom, power and life, but you spend it taking from each other. I cut you off from my knowledge from this day forward, I will interest not myself with your doings. I strip you of the power to walk the surface of Afa, that you may only affect the first of my creations only through your worshippers from this day forward. To ensure this, I will make for myself a home on Afa, to keep check on you, though you be cut off."
The Goddess descended to the Isle of the Goddess, but the powers, her children, were now angry at her. Many of them wished to destroy her, while a few desired she only change her mind. The powers of evil and chaos, being the most rebellious and wicked, set their worshippers to work to bring down the Goddess on Afa, but the powers of good have started to ally their worshippers against them, and thus was the Order of the Goddess created.
SPAN<The Goddess took some of the portfolios of the fallen gods. She took back into herself the power to control the magical forces, weather, and cause plagues. She holds other powers until such time as she finds mortals who are worthy to hold and use them.|^blue text^>
SPAN<She sits on her throne in what appears to be a stupor. She is, in reality, keeping an eye on her created children and those who have replaced her children after the godswar. She manipulates the magical energies and maintains the weather. She may set loose a plague upon a whim or in a calculated maneuver to control a population. She knows all that passes on Afa. She lets nothing interfere with her vigilant watch on the world she created.  The breadth of her power has yet to be seen.|^blue text^>
SPAN<There is no official church for Aleena. She has no priests and grants no spells to her followers. The Order of the Goddess does not get spells from her. Those who follow Aleena do so as a labor of love. They are the ones who watch the other churches and make note if one is getting too much of an upper hand. The appointed leader of the church makes his or her way to the Isle of the Goddess to report such matters, but can sometimes come away with a feeling of not being heard. The Goddess does listen however but, since she already knows what is going on, does not respond. The person who comes to her may never be aware of the gift she gives each time he or she visits. (This is usually a +1 to an ability score or a saving throw, but it could be as different as something beneficial on the wild magic surge chart.) She actually enjoys these visits since it gives her the prospective of a mortal. The more information the mortal gives her, the more beneficial the unknown gift will be.|^blue text^>
