#!/usr/bin/perl
use strict;
use warnings;

use CGI::Carp qw(fatalsToBrowser);

use lib "../../../files/lib";
use Base::Page qw(page story);

page( 'code' => sub { story(*DATA) });

__DATA__
A group of young elven women became tired of being cooped up in their staid elven village. They were rebellious and feeling adventurous. Together, they planned an excursion to the city of Tantras. They did not know what they were going to do once they were there, but they thought it would be better than what they were doing right now.
Their parents were not thrilled with the idea, but they could not deny their daughters the right to come and go as they pleased. The fathers gave their daughters stern looks, while the mothers gave advice on what they might expect in the city.
The trip took about a week. During that time they decided they would have to find employment in the city rather quickly. The employment they found was not what they had in mind. Shortly after arriving the whole group of women were captured by a band of thieves. The thieves used them for themselves, at first, and when the women became more pliant and stopped resisting, they were put to work in brothels. The women were terrified. After a while their captors were caught for unrelated crimes, and they were shortly forgotten. The guards over them disappeared. The brothels shut down one by one. They had no where else to go, and with the skills they had learned in the brothels, they decided to open one up on their own. They brought together all the money they had stashed away for an escape, settled down in their business, and waited for customers.
The wait was not long. The customers were slightly put off by the fact the women were not human. The ladies' beauty made some of them self-conscious, some outright rebellious, and some violent. They needed protection, and they needed it fast. It came in the name of Zendelic.
2 Kymaria Zendelic
Miklovik Zendelic was a budding businessman at the time. He ran a small trading company and saw this as an opportunity to get a little richer. He moved the ladies' establishment to a slightly better part of town and set them up as an escort service for the wealthier men in Tantras. After about a year, disaster struck. The ladies had not taken precautions, and they were all pregnant. Some had become constant companions to some of the richer men in Tantras, but more often than not, they had no clue as to the identity of the fathers.
Kyona Me'tronyara, the Madame of the brothel, went to her employer and told him of this problem. Instead of being enraged and belligerent and throwing them out on the streets, he made them more comfortable until they were able to work again. That was when he found out he was one of the known fathers. Kyona was carrying his child. This did concern him. He had just married. His new bride would not take the news her husband had fathered a bastard child lightly, nor would she like the fact her husband was running a brothel. All he said was Q<Anri will not be amused, but I will see the children will be born healthy.> He then dismissed her.
Kyona and the others all bore their children within twelve months to a year and a half later. The ones who had the constant services of a certain lady were deemed the fathers of some of the children. The children without known fathers were taken to the elven village first. When they were not accepted, they were taken back to Tantras and given over to several religious orders in the city and the surrounding area.
When they knew they could no longer work for Miklovik, they pled with him to release them from their work. He was not a cruel man. After the row he had with his wife, he let them go. A few of the women stayed in Tantras for a few months to stay near their infants, and some even took religious orders to be near their children who they could not claim.
Miklovik took his own daughter home to raise her. His wife Anri was not pleased with the arrangement, but after seeing her new charge, her heart softened. She would always have a look of steel in her eye when she looked at her husband, but with her adopted daughter, she showed only love. The girl's name was A<Kymaria|href="../#Kymaria_Zendelictronyara">.
Anri enjoyed her daughter, but saw something missing in her life. She knew what it was but she did not know who Kymaria's birth mother was. She steeled herself for the talk with her husband and told him Kymaria needed time with her mother. Miklovik knew Kyona had gone back to the village and was surprised Anri would make such a request. The next day he sent a message to the village and received a response within a month. The response was the arrival of Kyona. Anri and Kyona looked each other over, and neither entirely approved. The only thing they agreed upon was Kymaria. She was growing to be a wonderful child, and from then on Kyona would visit once every other month. On a few elvish holidays, Kymaria was even allowed to go to the elven village with her mother. Those times were always a joy and strain on Kyona, since she felt it her duty to teach her daughter of the elven ways.
Some were not as lucky as Kyona...
2 Sorack Linsandin
Solina Ca'viniar’s enraged father came for her soon after she had been delivered of her son A<Sorack|href="../#Sorack_Linsandinviniar">. Solina's father ordered her to give the child to its father and come home. He gave her only one day to do it in. She begged to take the child home with her, but her father would not have a half-human in his home, it was bad enough she had one. She hurriedly went to Kyona and asked for aid to find Rechek Linsandin. After finding the young Rechek, she laid the tiny infant in his father's arms and fled in tears. All she told him was he was the father and she could not take the child home with her. Rechek was stunned. He did not know what to do with a child.
He took the child inside his home and showed his new son to his own father. The fury of Rechek's father was even worse than Solina's. Rechek was devastated when he was dismissed from the house with only his few possessions. He was so shocked, all he knew to do was to look to his father's faith for guidance. He prayed to the Red Knight for the ability to plan a future for his son so they could thrive.
After many years they were living in near poverty. Rechek only had enough money to buy the necessary food and clothing and nothing more. When Sorack was fourteen, Rechek found him employment at the Zendelic Shipping Company. Sorack was not happy there and was more often moping then working. When Sorack was not working, he was studying. He had to teach himself to read which lead to an interest in magic and, paradoxically, in swordplay. He read of powerful mages and mighty knights and wanted to be both. He asked his father for aid, and his father told him to pray to the Red Knight for guidance in planning a strategy to gain what he wished. Sorack became devout but only to a point.
One day while working at the warehouse, Miklovik Zendelic noticed his drooping shoulders and called Sorack over. From a distance Sorack looked to be human. When he got closer, Miklovik was surprised to see a half-elf, one who looked to be the same age as his now spoiled daughter. Sorack never had a chance to meet his ultimate employer, so he didn't know who this human was, but seeing a kind look in Milkovik's eye, he said he wanted to be home reading or practising swordplay, even if he had to use a shaved off stick to practice with and hurting only the fence posts.
Miklovik liked this boy, and through their conversation, learned of his parentage. Remembering the story from Kyona, he soon felt a special kinship with the boy. If it weren't for Miklovik running the brothel in the first place, the boy might not be alive today. While they were talking, a fiery young girl entered the warehouse demanding to speak to her father. Miklovik looked appraisingly at Sorack, and secretly, with relief. He had found a "playmate" for his very temperamental, and often untrustworthy, daughter.
To make it easier for the two to "play" together, since the ranks of the fathers were too far apart, Miklovik found Rechek and promoted him to manage a warehouse right on the Zendelic wharf. This gave Rechek a pay raise to more then he could have ever dreamed. Soon after his father’s promotion, Sorack got a message to report to Miklovik. Fearful he had committed some grave offence, he was quite ready to run. Instead Miklovik introduced him to Kymaria. Kymaria looked Sorack over, while Sorack looked Kymaria over. Both were not impressed.
Kymaria asked her father why she was being introduced to Sorack. When told he would start to take lessons with her, she made a face and groaned. Sorack wondered why he was being given this rare honor, then wondered if it was an honor at all when Kymaria stormed out of the room in a fit of pique.
They eventually became friends, though Sorack's inability to do anything sneaky irritated Kymaria. On the other hand when Kymaria confided in him she would break into houses just to leave a white handkerchief, Sorack nearly gave up there and then. The incidents of white handkerchiefs were almost legendary in Tantras, and he did not want to know any more. Kymaria then giggled upon seeing the grimace on Sorack's face and told him she never took anything. Not knowing whether to believe her or not, Sorack let it drop in hopes this time she was telling the truth.
Kymaria did not let things drop. She plopped very unladylike onto the ground and began to tell what she had done. She would break into a house or business and look around not touching a thing. After she had a good look, she would turn around, retrace her steps, and leave the house. The only evidence the house had been burglarized was the white handkerchief she would leave attached to the place where she had gained entrance.
After that day Sorack would never look at his friend the same way again, but he could find nothing wrong with just looking. Kymaria also had the idea of starting a company of her own one day. She would break into a house, look around, and then in the morning , she would send a representative to see if her company could possibly offer its services if any needs were apparent in the home. Sorack groaned and went inside to study.
And some were luckier than Kyona...
2 The Marders
Decori La'bastiar, after having her son A<Driastan|href="../#Driastan_Marderbastiar">, decided to stay in Tantras with the child's father. She knew these relationships don't usually work but was willing to give it a try. She raised her son in his house, and when he was nearly six months old, she was pregnant again with A<Desolenna|href="../#Desolenna_Marderbastiar">. Her lover, Irnian Marder, was as pleased with the second pregnancy as he was with the first. Thought Irnian never married Decori, they lived as husband and wife. Decori raised her two children as best she could but soon found the call of home growing stronger. She knew her children would not be accepted in her father's house, so she decided it was best to leave her children with Irnian. Irnian was distressed Decori was leaving, but he knew he could not keep her. Driastan was eight years old, and Desolenna was six years old. Both of them wept when their mother left, but she promised to visit them often.
A few months later Decori found Kyona in their village. Upon hearing Kyona was going to Tantras to visit Kymaria, Decori asked if she could join, and Kyona agreed. They both knew the roads to Tantras can be bad for a single person, especially a woman, but two people would be less likely to be attacked.
After a few years, Driastan and Desolenna got to meet Kymaria. Driastan was fourteen and Desolenna was twelve. They did not stay long in the company of their new acquaintances since they wanted to visit with their mother more.
And then they were adults...
2 Coming together
Desolenna was in a state. Her father Irnian was in a rare bad mood, and he had ordered her to enter the temple like Driastan had. Desolenna didn't want to have much to do with the temple, but it looked like she would have no choice. She hated being given ultimatums, and in this case she just wanted to run away. She knew it was a bad idea, but in her state she wasn't thinking clearly.
She stumbled out of her house and went down the wharf. She walked out on one of the piers and stood there contemplating jumping in. Before she got the courage to do it, she broke down into a fit of sobbing. That is why she did not hear the two people walking hastily towards her. It took a loud throat clearing to get her attention.
She looked up and didn't recognize them. On the same token, they were trying to place where they had seen her. It was Kymaria who knelt down and gave her a hug. Q<Whatever it is, just keep crying it out.> was all she said.
After the tears had come into reasonable control, Kymaria withdrew a handkerchief and handed it to Desolenna.
Q<I remember you, aren't you Desolenna Marder?> Kymaria asked.
Q<Yes,> she responded in a quivering voice. She finished wiping her face and eyes, and looked up. Q<And you are Kymaria and Sorack as I recall. My mother is Decori, she introduced me to Kyona, your mother, Kymaria, you, and to you Sorack,> nodding in his direction.
They both smiled, and Sorack joined Kymaria in sitting on the pier. They struck up conversation before they got around to asking why Desolenna was standing so close to the edge of the pier.
Q<Now, tell us why you looked like you were about to jump off the end of the pier,> Kymaria said. Q<You gave Sorack and me a fright. We were on the other end of the docks when we saw you. We got here as fast as we could. Thankfully you sat down to think about it.>
Seeing Desolenna was hesitant, Kymaria and Sorack smiled in encouragement. Sorack sidled closer to her and put his arm around Desolenna's shoulders hoping it would help. It seemed to work when she started speaking.
Q<My father wants me to join my brother's temple. I just don't want to, I mean, I really like to gain knowledge but I don't venerate it like my brother does. I mean, I could do it if I had to, but I wish I had another option. I have to find another quickly, or my father might just send me to mother for a while," she sighed softly. "I really love my mother, but I have been to the village on very rare occasions, and I know I would not like living there.>
Q<What would you like to do?> Sorack asked.
Q<Well, I would like,> and then she hesitated.
Q<You can tell us. We are practically tribe mates, you know.> Kymaria said laughingly.
Q<Well, I would like to study magic. I want to be a sorceress, but I don't know where to go to find someone to teach me,> she said the last in near desperation.
Q<What are tribe mates for, if not to help a fellow tribe member. Come on, let's go talk to my father. I have a tutor of my own, and Sorack is studying with me. I don't think it would take too long for you to catch up.>
Kymaria then stood and offered a hand to Desolenna. When Desolenna gripped it, her life was changed. Kymaria and Sorack walked her back to the Zendelic estate and talked Miklovik into letting her take lessons. Kymaria even used the reason saying she had to help a fellow tribe mate in trouble. Miklovik could not resist. The only stipulation was Kymaria, Sorack, and Desolenna would have to spend some time in the company to repay for at least part of their education. They agreed.
Later, Driastan started to come in with his sister and help out. Miklovik really didn't like this new arrangement, but if Desolenna's brother wanted to help, so be it.
Kymaria and Sorack were not as studious as their new classmate. Their teacher, Arman was always peeved when those two would leave to do other things, but with the addition of Desolenna, he was mollified to have at least one student who would not be leaving to learn how to lop heads off with barbaric swords. He was also surprised she wrote down everything he said. When asked she said she was taking notes for her brother who was now a Lorekeeper. Desolenna was very behind Kymaria and Sorack since they had been in his classes for four years; but with her intense focus, she was catching up quickly. She was so pleased to have found a vocation, and her father was mollified.
After a while Sorack would spend time with Desolenna. He found her presence soothing. On the other hand, Kymaria was becoming attached to Driastan. Driastan's love for hearing her tales saved Sorack a few headaches. Desolenna found Kymaria engaging, someone she could confide in on womanish issues; while Sorack and Driastan would discuss theology though Sorack would usually learn more from Driastan than Driastan from Sorack. Driastan always took notes of the conversations. This did not mean Kymaria and Sorack did not like to be in each other's company any longer. It was quite the opposite. With the addition of Desolenna and Driastan, they became better friends.
2 A night out
Q<Come on Driastan, drink up, its a holiday!> A merry male voice yelled.
Q<You can drink enough for both of us, Sorack, but I am in the middle of something and want to get at it first thing in the morning.> The soberer of the two men said from his seat at the table.
Q<Alright, Dri, have it your way. I hope you don't mind if I get drunk.>
Q<Not one bit, tell me how you feel in the morning though, I would love to have an account of a hangover written down in my journal.> He smiled.
Q<I doubt you will get one from Sor, dear brother, he will probably not get out of bed until the headache goes away.> The woman sitting next to Sorack says.
Q<Well, I am not planning on getting that drunk myself, since I have to study spells tomorrow. Ever since my father learned that I was going to be a sorceress, he insists that I keep at it. I also have to help with the inventory, and you know what I<that> is like. Anyone want a few extra gold tomorrow, I am sure father would approve of it.> This said by the woman sitting next to Driastan.
Q<Kym, I love ya like a sister, but the last time I volunteered to help, your father nearly knocked my head off.> Sorack said.
Q<Sorack, if you had been where he told you to be, you wouldn't have been in the position of getting hit by the sacks he was throwing.> She giggled, along with Desolenna.
Q<Dri, will you at least have one drink, for a toast?> Kymaria said.
Q<That shouldn't hurt me too much, so order me an ale, and we can toast, so I can go home and get some sleep.> He yawns. Q<I've been working on this for days. I need more time in a day, any of you wizards know any spells that could give me the time I need?> He smiled at his companions knowing how they dread it when he gets inquisitive.
Q<Dri, you know every spell we have, and you know that we hardly get out much, especially since father hardly lets us out of the house yet. He can't quite grasp the fact you are now out of your novitiate, and me out of my apprenticeship.> Desolenna complained. Q<Can't you have the high priest talk to him? Once he realizes that you are an adult now, he might get it through his head that I am an adult too.>
Q<I will ask, after I get this paper done I am working on for him.> Driastan stretches. Q<I have been sitting too much, but it is so much fun to accumulate knowledge, don't you think?>
Q<Right now, all I want to do is forget all that tonight, and celebrate.> Sorack said.
Their round of drinks arrived, and they all picked up their flagons.
Q<What shall we toast to?> Kymaria asks playfully.
Q<The Beloved Outcasts!> Sorack replies, cheerfully.
Q<The Beloved Outcasts!> The rest of them raise their flagons, touch the brims, and then drink deeply.
The bartender just looked over at the table of youths and shook his head. He just wished that he could throw them out. Beloved Outcasts indeed, they should never had been born, half-elves, never trust them.
2 The path out of Tantras
Seeing his daughter had finally found friends, Miklovik was relieved. They kept his wayward daughter in control while not loosing her youthfulness. He started to include them in family gatherings, and even included them in some of his business dealings. One day a elven woman walked into his offices. She was exotic to say the least. She had a tiger pacing beside her and what looked to be a small version of a dragon perched on her shoulder. It was A<Baroness Aegyn of Valachan|href="../#Aegyn_Valchae">, the mystical island which appeared in the Sea of Swords. She was hiring a few ships to export some of her island's goods and importing items they needed. She did not have time to tarry, but an aura of adventure was about her.
Looking at the four children, nearly adults, he knew one day they would leave Tantras and seek out whatever the gods had planned for them. Kymaria was likely to be the first of this group to want to leave. He would ask Sorack to accompany her of coarse. He would send them all out together, but he knew Irnian would want his children firmly in their occupations before he would allow them to leave, especially Desolenna, since she was younger than the others by two years.
But that was the future. He prepared for them all. He could not do as much for the Marder children nor Sorack, but he made sure they had a fallback just in case.
No one knew Aegyn had been watching the four youths. She pondered them while dealing with Miklovik and tapped them for membership into a very A<elite group|href="The_Society_of_Divided_Light.pl"> of people. Aegyn is a member of a secret organization of people called the Society of Divided Light. A few months after Aegyn left, a stranger came and applied for a position within the Zendelic Company. She was a half-elf, and since Miklovik had a soft spot for half-elves, having a half-elven daughter might have something to do with it, he hired her as a dock guard. Her name was A<Carri Notha|href="../#Carri_Notha">.
Carri made herself indispensable around the company. She went out on a few voyages, but mostly stayed at the main warehouse. She watched the youths progress in their studies, and she started to give pointers. That lead to more intimate contact with them. They started to ask questions about adventures, adventuring, and other things. She was happy to answer their questions, but Miklovik wasn't. He knew Carri was a mercenary and not the kind of person he wanted around his daughter. He could not find a way of restricting the movements of his savvy daughter, nor did he want to fire Carri.
A while after Carri's arrival, the four wanted to go adventuring, making it harder for Carri, so she contacted her superior in the Society. She was told to remain at the company headquarters, and others would watch them on the road. Carri was half-tempted to open her spellbook up to the three fledgling wizards, but knew it was not permitted. They would have to find their spells on their own.
Carri soon watched them leave Tantras and seriously got into the business of being a guard. It was not the best job, but it was work until she found something more profitable.
