#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib 'files/lib';
use Base::HTML qw(html story);

html( code => sub { story(*DATA) });

__DATA__
Some of my views are unsupported by fact and may offend. I am open to others' opinions, though I may not change my mind. If you feel strongly about any of these issues, please send me an email to tell me what you think. You have the power to change my mind, and if you do, they will change here accordingly.
2 Drugs and alcohol
I am for keeping all the illegal drugs illegal. I do not want to even talk about them. I do feel that the drinking age should be lowered, and there should be no penalties to parents who want to allow their children to drink in the home as long as there is proper supervision. Because of my early exposure to alcohol, I drink only on rare occasions.
3 Prescription drugs
The Food and Drug Administration of the United States really needs to get off its butt and get to work on getting some of the drugs from Europe tested and approved. It is sad some of the comforts of life that Europeans have because of drugs they have had for years aren't here in the U.S.A. yet. Some of the drugs used in Europe are not approved for use in the U.S.A. had been developed here. Isn't it ironic?
2 Population control
I feel if we do not stop overbearing now, there will be more people finding out that they are infertile. If you are infertile you should not fight it, just accept it. It may be that evolution is telling you your genes are not necessary any more, or God does not want you to have children. Either way you shouldn't try to have children. I feel infertile couples should adopt, especially those children who are hard to place.
I do not like the way suburbs are popping up all over the place where farms used to be. It tells me the area is overpopulated. The local governments should start promoting birth control if the area can not support itself agriculturally. If a worst case scenario happened and the locals had only the local farms to get their food from, could the area handle it?
I feel allowing same sex marriages is a good idea. At least they are not starting off with the assumption they will have children. I also feel polygamy and polyandry should also be accepted. What is wrong with a person showing the world who he or she loves, even if it is more than one or the same gender?
Abortion is also needed in some but not all cases, and anyone who wants one should be able to get one. I do not feel it should be used as a form of birth control, but if a person has been abused and the result of the abuse is a pregnancy, the pregnancy should be aborted if the woman chooses. Choice is very important. I think adoption should be promoted more than abortion. There are a lot of people who want children who can't have them. The more children there are to adopt, fewer fertility drugs would be needed.
I think there should be a Childbirth Tax to be used to pay for education. It would give education a big boost and allow for a better teaching environment. The child's Social Security card and the birth certificate can be held until the tax is paid. This tax would also be a form of birth control. Only those who can afford the tax would willingly get pregnant. Having children in this day and age should be considered a privilege not a right.
I feel that there needs to be higher standards in schools today. There is no reason that a person should not be able to read and write on a high level in his or her native language when he or she graduates. I also feel that the United States should once and for all make English (American) the official language. It is the language of business these days. Why not make it official?
3 Abortion
The only way to rid ourselves of abortion is to rid ourselves of unwanted pregnancies. There are plenty of ways to attain this goal.
Abstinence is one way to stop unwanted pregnancies. This way is the most sure way, but is it the most practical approach? It is not. With sex being extremely pleasurable, the general population will not embrace this method. If sex weren't so pleasurable, we would not have the issue of abortion. Who would willingly have sex if it hurt?
The next way is contraception. This is the most practical approach to this issue. There are so many contraceptive drugs and devices from the pill to hysterectomies. It is just choosing the right method for each person.
Sexual education should begin when a child becomes a young adult. When a girl begins menstruation or a boy notices his first body hair is a good indicator that education should begin. This education should include everything from the mechanics of sex to sexually transmitted diseases to pregnancy. Part of this education should include an extensive discussion on the various forms of contraceptives.
3 Pills for erectile dysfunction
Any man who takes a pill for erectile dysfunction should be required to get a vasectomy. Nature is telling you something guys. No kids! Infertility is nature's way of giving you a free pass to have fun. Let the fertile people have the kids, you enjoy being free of that burden. I would fund research for infertility so more people could have it.
2 Religion and politics
I do not like that religious officials are running for political offices. Those people are not going to represent their constituents, just their religion. That is wrong. I also think that the government should not support any religious organization, no matter what the cause. Religious organizations should be supported by their own membership. If the membership can not support the organization, maybe the organization should disband. I do not think that religious symbols should be removed from public buildings that have historical value. I am against any new incursions of religion added to those same buildings. If there is to be a religious display, it should include all religions, mainstream and otherwise, even if the religion is not accepted by the majority.
Science suffers as long as religion is used for profit. When religion pushes to have science removed from publicly funded education, the children and our future will suffer. If a church pays its ministers a salary, it's a corporation that should be taxed like any other corporation.
2 The Second Amendment
I feel the Second Amendment of the United States Constitution has been grossly abused by those that just want to own a gun for fun. The Second Amendment is there to insure that there is a well armed militia in case of emergency. I don't know of any government recognized militias in my area. If a person wants to own a gun, they should be part of a government recognized militia. Those members should have to pass rigorous tests; mental, physical, and psychological. They should have to report in on a regular basis for extra training. I don't feel there is a need for hunting. If the population of a certain animal is growing too much, the government should try to find out why. If it is because their natural predator has been removed from the ecology, then try to reintroduce it or introduce another non-human one.
2 SOPA/PIPA
I am against the Internet Blacklist Legislation also known as Protect IP Act in the Senate and Stop Online Piracy Act in the House of Representatives in the United States of America where this site is hosted.
2 Use of language
You have something to say, and you have found just the right place to say it. You created an account on the web forum, and you start typing your first message. You are excited because you have found like minded individuals with whom you can share your views.
You have been typing away for five minutes, and you have about a page worth of material. You are excited about the idea that you are sharing. You hit the submit button, and the thread has been started. You get a few replies and wonder why you aren't getting more. It seems to be an issue into which everyone on the forum would really sink their teeth.
Does your audience understand your message? Can your audience make it from one end of a sentence to another without having to do mental gymnastics to try to figure out what you are saying? A typographical error or two is all right, but if the people you are trying to reach have to re-read what you have posted just to figure it out, you may just lose their interest. How is your grammar? Do you know where the commas need to be, did you use proper capitalization, how many spelling errors did you make? Did you try to correct your errors? If you have too many errors, guess what, your message is going to get lost! For something as important as the issue you want to discuss, you should try harder to make yourself more clearly understood.
The internet is warping our proper use of language, no matter which is our native one. I am sure that every language has some sort of internet shorthand to it. This shorthand is acceptable in some instances, like chatting. Other than that, I feel, people need to make use of the power of proper language to express themselves. They can not do it if they do not use language properly. It does not matter what language it is. If you are posting in French, then do it per the French grammatical rules. The same for any other language, and don't forget dialects. Even some dialects have their own written grammatical rules.
I know that there may be mistakes in this. If I find one, I will try to correct it as soon as possible or repost it with the corrections. I want my readers to clearly understand what I am saying. If a reader can not, I need to try harder and look closer at what I have written.
Please, I beg you, proofread your work, then send it to us to read. (I try to practice what I preach, however, it does not work out as well I would like.)
2 Random opinions
I am for women being able to go topless, however, I am too indoctrinated against to just let hang out that I would not go topless for long.
To get better election results, we need a better majority.
Our government wouldn't cost us as much if we stopped asking for so much. It should be the last place to go for help.
Nothing is unnatural if you trace its construction back far enough. There are natural protons, electrons, & neutrons used.
Sometimes I can't wrap my head around the thought that I am an end result of two single celled organisms getting together. We may be related.
