#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib '../../files/lib';
use Base::Page qw(page story);

page( 'code' => sub { story(*DATA) });

__DATA__
She wakes up from sleep.  She feels refreshed and renewed, but only for a minor ache in her head.  She goes to stretch and notices that she is already stretched out.  She tries to roll over, and at that moment she realizes her hands and her feet are tied to a bed.  The cords are silky smooth.  They will not leave marks on her.  She knows she is trapped and panics.
During the time she tries to move, the flesh of her back and her buttocks rubs against the sheet on the mattress.  Her clothes are gone, and she is naked under the sheets.  She is afraid.
A door opens.  They are dressed in robes and their heads are covered.  They slowly enter the room.  Their pace is slow and deliberate.  They carry something long in their hands.  Six of them surround the bed.  They turn the rods they hold and slowly place them into the floor.  The posts have peculiar holes at the tops, slits actually. They bring in flat boards that are covered with foam and the same silky cloth.  These they slowly slide through those odd holes, from her right hand side.  They connect with the posts on the other side of the bed.  Her body is raised up on these boards.  The cloaked people then slowly remove the mattress from the bed.   They come back in and lower the frame of the bed.  Then they place a thinner mattress on the frame and slide that under her.  It is to low for her back and her buttocks to touch, and there is enough room for another to slide under her.  They turn and leave.  She feels like screaming.
The door closes.  From somewhere in the darkness more people appear.  She can tell that they are there from the difference in the darkness.  She can tell that they were not clothed for there was no sound of cloth on cloth.  She knows what was going to happen.  They surround the bed.  She hears the bed groan with the new weight upon it.  She cannot tell how many there are.  Panic again surfaces in her mind.
Silently they probe her body.  They touch her every part.  Her hands are caressed as are her feet.  Her arms and legs receive a gentle massage.  Her back is rubbed and she becomes relaxed.  They rhythmically touch every part of her body to relieve the tension from her muscles.  
When she seems to be suitably relaxed, their probing hands probe elsewhere.  They touch her breasts.  Massaging them, her nipples rise to become like perfect cherries to lick; yet they are left untasted.  Her buttocks are rubbed, yet they are not separated to any noticeable extent.  Her clitoris is then touched, but only like the flutter of bird's wings.  The touching, the rubbing, and massaging take their toll on her.  She wants to tell them how to please her, but her mouth is gagged.  She cannot speak only sigh in pleasure.  Her cheery-like nipples then are tasted.  The tongues of the unseen people flit on those cherries and nibble.  They are sucked and twisted with the same expertise as someone who is a lover of cherries would lick the fruit.  Both are licked and sucked at the same time, she moans in appreciation.  She feels the hot breath of these people on her stomach.  The kisses travel from her stomach to pleasure her elsewhere on her body.  They lick and suck her clitoris.  Teeth are ever so gently applied to this area of her body, and she lets out an even greater moan of pleasure.  A tongue is thrust into her vagina.  She moans her pleasure through the gag..
The space between her buttocks is opened. She feels the hot breath of another.  Another mouth and another tongue are put into play.  She wants to scream her ecstasy, yet she cannot, for she is still gagged.
The gag is removed from her mouth, only to have it replaced with a phallus.  It is long, yet still limp.  She gently breathes on it.  Her mouth, on it's own accord, wraps itself around the penis and begins to rhythmically move on it.  Only then does she give back part of the pleasure she has been receiving.  Her pleasure is becoming intense.  They are nipping at her breasts, sucking on her clitoris, kissing her buttocks.  Her breasts ache from the attention, yet they cry out for more.  Her clitoris becomes sore from the teasing tongues, yet it also screams for more.  Her vagina grows round, yet it becomes peculiarly tighter.  Her whole body wants to be released into climax that these people are denying her.  She moans and cries.  The penis is removed from her mouth to be replaced with another one.  She sucks it, licks it, makes it erect.  She toys with it.  Her lips press on it, and she moves her mouth up and down that incredible shaft.  Her tongue explores the very tip, and the penis bobs its head in appreciation.  That penis is removed and another inserted, yet another in a series.  There seems to be no end.  She gives each attention, the same attention that is being given to her body.  Then she feels penetration.  Her body is filled.  One enters from the top, the other from the bottom, and yet another still in her mouth.   She is thrilled.  She soars.  She would sing if it weren't for the penis in her mouth.  They move together as if one mind controlled all of those penises.  In goes one while another retreats.  Back and forth they volley as if they were playing tennis, and her body is the ball.
They are all removed. The gag is replaced. She is on a plateau.  She wants more.  She is soon reengaged.  The strange game starts once again.  Her breasts ache even more, yet they still receive attention.  Those lovers of cherries are not to be denied.
The frenzy of the pleasure sends her into a state of bliss.  Her body burns with sexual fire.  Wave after wave crash over her.  She rises to the peaks, higher and higher.  The bodies move faster and faster.  She cannot keep track of the pace.  The bodies rub against her.  Her breasts are getting pulled this way and that.  Her nipples are pinched and sucked and bitten.  These that are pleasuring her became like animals, yet they stay on target.
Their pace takes on a new frenzy.  The rubbing on her insides cascades over her.  Her body sings out its orgasm, in tune with the orgasm of the two that are pleasuring her.  She bites through the gag and screams in pleasure.  She exults in her release.  Then she falls back on the boards that have supported her and sleeps.
