#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib '../../files/lib';
use Base::Page qw(page story);

page( 'code' => sub { story(*DATA) });

__DATA__
2 A Distraught Friend
I got a phone call the other evening. My friend Andrea was in a very pissy mood. I could tell just by the way she was spitting her words out at me. The last time she called me in this mood, I ended up spending the rest of the night on the phone with her. I was really annoyed, because this call had interrupted me in the middle of one of my best created fantasies to date. I had lost it, and that also pisses me off. I started to snarl back at her.
"Will you please get to the point Andrea?" I almost yelled at her.
"What is your fucking problem, Diane, did I interrupt something more important than my ruined life?" she yelled back at me. She was not used to me standing up to her. She usually just walks all over me, and I let her, because she doesn't have that many people here that really care. She just moved here a few months ago, and made the mistake of being a little to open about her lifestyle.
Then, she started to cry on the phone how she just broke up with her newest girlfriend. I sit there and listen for the next two hours about it.
By this time, my mood had definitely shifted. I was getting increasingly angry with Andrea, even if I knew I shouldn't. She seemed to need me right now, but I was still lying in bed, naked because of my fantasy, that she seemed almost too rudely interrupted. I was frustrated now, in more ways than one.
Another hour had passed, and she is still raving to me. I wonder what to do to shut her up. While she is ranting and raving on the phone, I cudgeled my brain for a solution to the problem. Her last girlfriend was a bitch, and used Andrea for her money and nothing else. At least that is what Andrea is saying. I just wanted her to shut up already. I know that I can't go back to my dildo now, it had fallen out of me after a while, since I totally forgot it was still inside me when I heard Andrea's tearful voice on the other end of the phone line. I didn't even remember when in the conversation it had fallen out of me. I looked down on it while talking to Andrea, and I started to swear mentally. I started to just agree with her on all things. It seemed to help a bit, since she calmed down a degree though not entirely.
After another hour had passed, and she still is talking about the same thing, her rotten life, I am still cudgeling my brain for a way to get out of this. I start to get dressed while she is talking to me and that is when the idea hit me.
I know that she is usually much calmer in person, since she will actually see my face or whoever's face it is, so she tends to try to not hurt her guest's feelings. So, when Andrea goes to take a deep breath, I tell her that I will come over to her place, and we can talk about it some more when I get there. I think to myself, that I will at least have some time to prepare for the onslaught.
"Andrea, I have to take a quick shower before I leave, so give me about an hour and a half. Can you wait that long?"
"Sure, Diane, but please hurry, I am so mad I could just scream the house down. I need someone to talk to, and you are the only one I can trust right now, and not have to try to create a story about a fictional boyfriend. You know I hate having to do that..."
Before she can go off on that tangent, I hurriedly speak up.
"Okay, I will be there in an hour and a half. Talk to you then."
"All right, Diane, I will be here. Just use your key to get in."
"I will. See you then." I then hung up.
I rushed into the bathroom and I took a very quick shower. I knew that if I let Andrea stew for too long that she would probably call again, and I didn't want that. I just threw on some clothes that were handy not taking into account that I was going into a nicer part of town. I threw a headband in my hair, and brushed it just enough to get the tangles out. I then grabbed my purse, pager, cigarettes, and keys and ran out to my car.
During the drive I went through the situation that was described over the last 4 hours, to see if there was anything that I could say or do to keep her calm, at least calm enough to tell me what was really wrong. Thank goodness she doesn't yell in person, just on the phone.
I get there in less time than I expected, and that gave me an edge too. She always watches the clock. That is another thing of hers, if you tell her you are going to be there at a certain time, you had better be there, or there would be hell to pay.
I let myself in quietly. I heard her in her bedroom sobbing. I checked one of her phones with an "in use" light on it, and saw that she was not on the phone. She seemed to be crying in her bathroom. I quietly slipped into her bedroom, and I sat on her bed waiting for her to come out. I took off my shoes, and I lay back on the bed. This is not uncommon for me, when I am at Andrea's. There isn't that much furniture around her place, and the only way to be comfortable is to lie on her bed when in the bedroom. I notice that I forgot to wear a bra, and I shrug. It doesn't really matter, she and I had an instant friendship, and it seems to be a genuine one, if not an inconvenient one sometimes.
She finally emerged, and her eyes widen when she saw me on her bed.
"You're here early." Andrea said a little surprised.
That is one other thing I learned about her, if you are early, she definitely is a bit more pliable. She came over and sat down on her bed, next to where I was lying. I was glad that it is a queen-sized bed, since it would be a bit cramped otherwise. She started to talk again, but this time a lot of the heat was out of it, and she was keeping a level tone. She told me how her ex-girlfriend had turned out to be a moneygrubber, and how she had coped with the girl stealing things out of her apartment. I was listening to her, and Andrea seemed to have calmed down even more when I got there.
During one part of her story, I reached over and gave her a hug. She then wiggled it around to where I was sitting with my back against the wall, since her bed doesn't have a headboard, and she was sitting between my legs, leaning back onto me. I sat there with my arms around her. Her voice lowered to a little below normal, but still clear. I realized that she had almost totally calmed down now. She was even talking rationally now.
While she was talking, her hands started to rub my legs. At first I didn't realize what she was doing, and I don't think she did either. My hands were just rubbing her shoulders, and running through her hair.
I did like rubbing her shoulders, and running my fingers through her hair. It was calming her down, and that was a good thing. She and I had been friends for many years, as pen pals. I had known she was a lesbian for quite awhile now, though I could not adopt that lifestyle. She had been patient with me when she first told me. I didn't write her back for a few months after I had found out. It had taken a phone call from her, long distance, for us to get the situation under control. I was pretty upset, since the plans I had had for a double wedding went right out the window.
I just held her there like that for a while, so she could get the whole story out, from beginning to end. My hands still worked on her shoulders, while she was talking. I would gently massage her scalp, and then run my fingers down from her scalp, over her neck, to her shoulders. She seemed to talk more when I was doing that, so I continued. I heard about the ex-girlfriend telling Andrea's parents about the relationship they had. That information totally ruined any chances of Andrea getting her trust fund, the one her grandmother started right before she died.
My hands seemed to have a mind of their own. They walked their way down her sides, and I gently pushed her to a sitting position, so that I could more readily rub her back. When I usually give her a back rub, she would take her shirt off so that I could get a better grip on her back. I really didn't notice that she wasn't wearing a bra, since she usually doesn't anyway. My hands went up and down her back while she was telling me how she was now the black sheep of the family, and that when she went home the last time, how she was treated like dirt, since she really couldn't deny what her ex-girlfriend had told them.
I was massaging her sides when she got done telling about the family reunion gone bust. My fingers would lightly brush the sides of her breasts, but I thought nothing of it, since it was part of the massage. She then leaned back into me, and started to tell me how her parents then told the rest of the family about her lesbianism. How she was now ostracized from her family. How she could never see them again, with the exception of one of her more liberal cousins, who didn't care either way. She told me about how he would give her tidbits of information on what the family was doing to totally cut her off forever. My hands were now rubbing her stomach. She was wearing only her panties at this point, having started this conversation with only her shirt and panties on. My hands were rubbing her sides and belly right down to the panty line to right under her breasts. My thumbs would brush her breasts, but I wasn't really paying attention to what my hands were doing, I was just paying attention to what she was saying.
She then wiggled between my legs, and that jarred my attention a bit, but not much. She was sighing a bit now, and I just thought that she was thinking about what she just told me. She was quiet then, thinking of something else to tell me, I guess. I was still rubbing her belly when she spoke up again. My hands have drifted up to her collarbone, and I didn't think about how they got there. I was rubbing right above her breasts now, my pinkies lightly brushing the tops of her breasts. She took a breath, and stated to tell me about how much money she is out of now, because of her ex-girlfriend. My hands drifted down to her breasts at this point, and I was rubbing them. I was still not really thinking about what I was doing. I was just doing it. It seemed so natural.
I didn't realize that her hands were rubbing my legs. They were on my knees and she squeezed my knees a bit when my hands drifted to her breasts. She went quiet again, and I started to think about the aborted fantasy I was having when she first called. I tried to think of what exactly I was fantasizing about, when it hit me. This is what I was fantasizing about earlier, being with a woman. Ever since I had met Andrea face to face, I had started to wonder what it really would be like to be with a woman. With that revelation, I went still, not with tension, just with a quiet revelation of my feelings at that moment.
It was also at that moment that I realized what I had been doing. A slow smile crept onto my face, and I realized that Andrea also noticed a difference in me, a subtle yet profound change in my view. She had told me a lot about what it is like to be with a woman, but this was the first time I had first hand experience. I liked doing this. So I continued, knowing from personal experience what I woman usually liked. My hands did not stay lackadaisical for long. I started to kneed her breasts like bread dough. They are not big breasts, but just the right size to fit into my hands, with a little extra to spare. My palms were on her nipples, and they were getting caught in the folds of my palms whenever I squeezed the whole breast. She stopped talking suddenly, and her body became tense.
"Diane?"
"Shhh, don't worry about it, Andrea, you need this," I whispered, as I was moving her hair off of her neck, then I kissed her neck tenderly, right behind her ear.
"Oh, Diane," she whispered, as she totally relaxed in my arms.
I then let my hands slide down, over her stomach, to her panties. I slid my hands underneath the material, so that my fingers were right above her pubic hair. I gently got them off from her hips, and down to her thighs. She wriggled them off the rest of the way, as my fingers were lightly running through her pubic hair. I was just combing it out with my fingers not yet touching the skin underneath. That seemed to have the desired effect on her. She sighed a bit, as I know she was trying to contain her impatience. My fingers just kept lightly combing out her vaginal hairs, even though it is too short to tangle at all. I let one finger drop down and lightly touch her nether lips, right where they part. She seemed to explode in my arms. Her breathing became ragged, and she pressed herself against my hands, but I was not going to give her what she wanted just yet. I wanted to give her what I wanted myself. Therefore, I toyed with her, played with her, and built up her arousal.
I looked over to her nightstand, and I saw that she still had all the "toys" she used to stimulate herself. I took one hand away from her vaginal hair, and I grabbed her vibrator. I placed it by my thigh, and I went back to teasing her. I let my fingers rest on her skin now, right under her vaginal hair, and my forefingers were resting right inside of her lips. They were on either side of her clit, I started to press them against either side of her clit, and she gyrated in pleasure. I started to kiss her neck again, and let my fingers start to explore her. I found all the right spots almost immediately. She used to share these things with me as well, having no one else to share them with. I didn't think I would ever use that knowledge, but now I was using it to the hilt. I fingered the outside of her vagina, letting her become more excited. I felt a trickle of wetness escape from her, and that is when I knew what I was going to do next.
I grabbed her vibrator, and I placed it right at her opening. I continued to finger her clit with my other hand, and with the same hand, I restrained her from moving herself to receive the vibrator. I wanted to tease her some more. She was so ready to receive it, that I couldn't just give into her, not now. I usually do anything she wants, and she wanted that vibrator. This time though, I wasn't going to be the passive one, the bending one. I was keeping it from her, and she seemed to want it more and more. I turned the vibrator on, letting it buzz at her opening.
She was panting at this point. Her moans were getting louder and louder. I then relented and slowly, ever so slowly, slid it into her.
She went wild. Her whole body was shaking when it finally reached bottom. Her eyes were closed, her hands grasping and ungrasping my knees. I couldn't believe what I was doing, but I was enjoying myself, and I was enjoying teasing Andrea, who had told me all of her secrets, that I was now using to my advantage. I then started to back the vibrator out of her, and then I slowly replaced it. All the while I was fingering her clit, making it swell, and making her wetter and wetter.
Her body started to shudder under my touches. She moaned louder and louder. I smiled and kissed her neck again, as I fingered her clit, and slid the vibrator deep inside her again. She turned her face so that the next kiss she received was on the lips, and it was, a deep passionate kiss, with tongues intertwining, and her body spasmed. She kissed me so hard, and she breathed so deeply, that I knew that she was having orgasms. She turned around so that she was facing me, and she put her arms around me, and just quivered in them. I turned the vibrator off, and just let her have one orgasm after another. My mouth found one of her breasts, I took it in, and I sucked on it hard. That got a scream from her. She bucked against the vibrator that I was still holding onto and that was still inside of her.
After a while, she calmed down. The vibrator slid out of her, and I let go of it. I let it fall onto the bed, and she was just lying beside me, panting, trying to regain her breath. In about a half an hour, she was calm.
"Diane? How did you know I needed that? Why did you do it?"
"Andrea, you tell me everything, and you have had such a hard time lately, that I just had to do something, and at the start, I wasn't even planning on this."
"So this was spontaneous, then?"
"Yes, it was. I didn't know it at the start, but it came to me that I have wondered what it would be like to be with a woman, and now I know."
"Well, dear, you have not fully been with a woman yet, have you?" and then she smiled. "I will just have to let you feel what it is like to be on the receiving end."
With that, she slowly unbuttoned my shirt. I hadn't realized that I had started to sweat.
"You need a cool off shower, so why don't you just take one real quick."
"All right, I will," I said. I really didn't realize that I had done so much work. I looked at the clock, and it was already 1am. That startled me a bit, but since it was Friday, it didn't really matter. I went into the bathroom and stripped off my clothes, and started the shower. I was trying to think of what Andrea was doing right now, but I really wanted to clean up myself. I hate feeling grimy. The shower was not set too hot, but it was just warm enough to be bearable. I stepped into the shower, and I quickly cleaned the sweat off of my back and legs. I rinsed my hair out, and shut off the shower and toweled myself off, quickly. I am not one for long drawn out showers. I saw that there was a spare bathrobe on the back of the bathroom door, so I put it on, not really wanting to put my clothes back on.
I walked out of the bathroom, and what I saw amazed me. Andrea was still bare, but she looked radiant. She had, in the short amount of time I was showering, brushed her hair out, and made her look better than she had before. Her whole body seemed to be so radiant. She smiled at me and I smiled back. I couldn't believe what I was doing, but I was, and I was happy about it.
She opened her arms to me, and I willingly went to their inviting embrace. She deftly opened the robe, that wasn't tied too tight to begin with. I relaxed in her arms, letting her be my tutor in the art of this type of seduction.
She opened the front of the robe, and laid her hands on my breasts. She did not move them at first, just laid them there letting me savor the feel of a woman's hands on them. I felt her long fingernails rest on my breasts, almost touching right under them.
Her hands then moved, very slowly at first, but a little movement nonetheless. I felt the palms of her hands kneading my nipples, as her fingernails lightly brushed the underside of my breasts. I felt my nipples starting to respond to the movement, my breasts swelling with arousal. While she was arousing my breasts, she was kissing and nibbling on my neck. That increased my arousal too, much to my amazement. I couldn't believe that this was happening to me, and more than that, that I had started it. My mind was filled with wonder at it all.
I felt her hands kneading my breasts with more firmness, and a little faster. I also felt her vaginal hair rubbing against my buttocks. It felt so good, so warm. Her kisses extended down my neck to my shoulder, and that was one of my more sensitive places.
She gently moved us so that I was then lying on the bed next to her. She kissed down my shoulder, and to one of my breasts, and I didn't try to discern left or right, it was marvelous no matter where these particular kisses were.
She kissed me around my nipple, and then over it, to go to the valley between my breasts to kiss the other one. On the return trip, her tongue would flick out over my nipples, and that made me even more aroused. She stopped suddenly, and attacked one of my breasts with abandon. Her hands were roving all over my body, from my free breast down over my stomach, and over my vaginal hair. I was in another world altogether. She was excellent in her seduction of me, and I was not going to try to stop her now. Her mouth was so warm, right on my breast, her tongue whipping out flicking my nipple and circling it several times.
With catlike grace, she moved over me to my other side, and there she attacked my other breast with her mouth, leaving the earlier one in the chill, still wet and glistening with her saliva. I lay there, my arms out flung, enjoying her attentions. She didn't miss a spot on my breast. After that nipple was red and firm from her mouth and tongue, she let it slip out, and just toyed with them for a while, keeping them erect. She bent over me to kiss the valley between my breasts, and then ventured into my lower territory. Her lips touched my stomach, all the way down to my belly button, and then beyond. She moved herself so that she was kneeling right between my legs, still with the catlike grace. Her lovely naked body was between my wide spread legs. Her kisses lingered right above my vaginal hair on my stomach, while her fingers started to walk up my legs, lightly, gently, smoothly up my bare legs. Her fingers got to the top of both my thighs at the same time, and with the same lightness and gentleness, they opened up my outer lips to reveal more of me to her. I saw her smile as she examined me, and I smiled when I saw that. Her fingers traveled into my cleft, and started to circle my clit. That drove me wild. Her light touches became more forceful, but still gentle. I laid my head back on a pillow, and closed my eyes. I could hear breathing speed up, as mine already had. I felt her fingers start to explore my hole, and when they went inside I could feel her hot breath right over my lips, and then I felt her tongue flick out, and touch my clit.
My whole body arched when she did that. She didn't seem to notice, since her mouth didn't move away, and her tongue stayed right on my clit, not moving even a fraction of an inch. As my body settled once again, I could feel her tongue exploring where her fingers once were. It traced a route around my clit and then it flicked my clit back and forth. That drove me over the edge. I started to thrash about a bit, but I felt her hands firmly on my hips then, and I couldn't move. She kept at my clit, and then her tongue went down to explore my hole. She was following her fingers up with her tongue. As she stayed down there, I couldn't help to play with my nipples. I made them stay hard, as she did her work on my private place. My head felt light and I felt as if I was floating. Her tongue dove deep inside of me, as if looking for something.
With her tongue probing me, her hands on my hips, and me toying with my breasts, I was very close to having an orgasm, and she knew it. Thankfully she didn't stop, but I did feel her move to reach for something, and that something was laid right at my opening, that I calmed just for a second, all she needed to keep me from climaxing to soon. She slowly let it penetrate my body, and to my shock, I did not feel it go into one hole, but it had a second prong I didn't know about, and that one went right into my anus. It was so smooth that it encountered no resistance in either hole. I had never seen this one before, and I was astonished to find that I liked it. I then heard a click a split second before I felt it vibrate inside of me. Both openings were being so aroused at that point that I didn't realize for a few seconds that she had continued sucking on my clit. With her hands free, they moved smoothly up my stomach, and when her hands met mine, she gently batted them away, and toyed with my breasts herself. I lost control when she took complete control of my body. My whole body thrashed underneath of her, with me unable to control it. I was so aroused by her that I lost all of my conscious ability to fight off the waves of pleasure that were building up inside of me.
She felt my orgasms coming and increased her pace on what she was doing. She pinched my nipples hard, and sucked deeply on my clit, as her body wedged the device into me more firmly. She was going so fast now, that I could not stop it as wave after wave of orgasms thundered through my body. All I wanted to do was to curl into a fetal position from the intensity of the orgasms. My brain wasn't registering coherent thoughts; I could only able to deal with the intense pleasure I was receiving.
After a while, she let up on me. She slowed her pace, and then gradually stopped. She turned off the double vibrator, and then slowly took it out from inside of my passion-wracked body. All I could do was lie there and tremble. She got up and out from between my legs and lay down beside me.
"Are you all right, Diane?" she asked me when my trembling was less noticeable.
"I...think so," was all I could say.
She lay there for a little longer. Her hands were gently rubbing my body, calming it now, though I was very sensitive.
"I know you enjoyed yourself," she said with a smile on her face and in her voice. "I know that I did."
I just lay there, and nodded mutely, not trusting myself at this time to answer coherently. She gathered me into her arms, and just held me for a while, while the tremors left my body completely, leaving me exhausted. I vaguely remember looking at the clock to see that is was 4am.
"Andrea?"
"Yes, Diane?"
"Thank you, I will never forget this."
"Neither will I, neither will I."
hr
A few weeks after what could only be called the incident, Diane and Andrea became even closer friends. They did not have any other sexual experience together, right after that, but that one night was enough. Andrea had found herself a new girlfriend, and Diane was very happy for her.
2 The Reversal
I came home from work that night, and like every other night, I would just walk into my apartment and drop my keys on the table by the door. That was my first clue that something was missing. My keys did not hit a solid surface immediately. I flipped the lights on and my living room was empty. All the furniture was gone. I searched the whole apartment, and everything except my clothes and a few other things were gone. I walked to my kitchen in a daze. I couldn't believe this was happening to me. It was then I saw the note on the counter.
He left me and took everything with him. He said in the note that since he had paid for most if it; it all belonged to him. I just couldn't believe it. He didn't even leave me any dishes and cleaned out the refrigerator. I had nothing left, nothing at all, except the clothes that I came here with when I moved in with him. He said that he changed the lease to just my name. He knew that I couldn't afford to replace everything and pay the rent. I broke down into tears. I picked my keys up off the floor and left the apartment. I got into my car and drove over to Andrea's new house. When I got there, I was still in tears. I got out of my car and dropped my keys again. I was picking my keys up a lot this night. I walked up to the door, almost tripping a few times on the steps. I didn't need to knock, I guess that I made a lot of noise when I was coming up the steps, the door flew open, and Andrea was there.
"Diane, what the hell?" she demanded.
She pulled me into the house immediately. My tears were still flowing down my cheeks. She sat me on the couch.
"Brenda, could you get a glass of wine for Diane? Please hurry." 
She then turned to me, pulled me into her arms, and held me there for I don't know how long. I was still unable to mouth the words. I didn't even notice that I had another set of arms around me. I just sat there and cried on Andrea's shoulder.
She pressed a glass up to my mouth at one point and told me to take a drink. I did what she told me, since I was unable to even think at that point. I was an automaton. All I could think about was my situation. Nothing else filtered into my mind, until I had a few sips of wine in me, and Andrea wiping my tears away with a tissue.
It was at that time that I noticed another couple there. I was so embarrassed. I could not believe that I had just broken down in front of total strangers! I mean, I know Brenda, Andrea's new girlfriend, but the other couple was totally new. The two men just sat there, looking concerned, as I continued to cry. I just couldn't stop crying. I felt that my life, as I knew it, was over.
"Oh Andrea, he left me with nothing but the clothes on my back and the lease to the apartment." I almost lost what control I had, but I had to tell her why I was in this state. "You know my financial state, I can't afford to replace the furniture."
She just took me in her arms again and held me there while I cried a bit more.
"Diane, why don't I take you upstairs and help you clean up a bit." 
Not trusting myself to talk, I nodded.
"Please excuse us for a moment," she said to her guests. "We shouldn't be long."
She helped me up the stairs to the bathroom and started the water going in the sink. She grabbed a washcloth from somewhere and dabbed my face with lukewarm water. She then brushed my hair and got all of the tangles out that I had unconsciously put there from running my fingers through it because of my anxiety. After my face was washed and my hair fixed, she gave me a brief kiss on the cheek and a tight hug and helped me stand up from the toilet seat.
"Feeling better?" she asked.
Q<Thanks Andrea, I feel a little better now, at least on the outside.> I gave a half smile to show my appreciation.
"Now, let's get you back downstairs to meet my friends." 
She led me back downstairs and got me a fresh glass of wine. I sat down with as much grace as I could muster which wasn't much. I wanted to crumple again, knowing that all the furniture in my apartment was gone. I was even looking around the house enviously. It had so much room, much roomier than my little apartment. I took a large sip from my glass. Andrea returned with Brenda, and they sat down on either side of me.
Brenda knew of the one night Andrea and I had had together, and she wasn't in the least bit envious of that. She understood it and was very eager to meet me the first time. Our meeting couldn't have been better. Brenda just came up to me, gave me a hug, and told me that she was very happy to finally meet the woman who had kept Andrea sane that night.
So there I sat with my two protectors sitting on either side of me. It seemed as if they were ready to intercept any negativity that was thrown my way. The men just threw reassuring smiles at me while Andrea did the introductions.
"Diane, I would like you to meet Brad and Peter," pointing the man on the left first.
They got up and came over to shake my hand, and Peter was even gallant enough to kiss it which made me smile.
"I met them at the Rainbow." I had been to the Rainbow once, with Andrea, when she was finally over her ex-girlfriend. I was told what kind of place it was and found it to be a nice place to go. Everyone there was friendly, and when I told a few of them that I was straight and just helping a friend get over a bad relationship, they smiled and just started small talk. That was fine with me, and I enjoyed my evening. That is where Andrea met Brenda. It was kind of cute, when I saw them together for the first time. I wished I had had my camera.
I digress...
"Nice to meet you both," I said, trying my best to put on a full smile, but most likely ending up with a sloppy one at best.
"Nice to meet you too, Diane," Brad and Peter said almost simultaneously.
That got me to giggle and my mood started to lift at that point. I have to admit now that Brad and Peter were extremely good looking guys. They looked like they both were gym nuts by the way they were built. I just had to give them a once over with my eyes. They seemed to have noticed and smiled.
"We get that all the time, Diane," Peter said, with a chuckle.
I must have blushed deeply. Andrea and Brenda seemed to relax then, since they both backed off a bit of their protective stances.
"We were just about to sit down and have dinner, and I think that a home cooked meal will do the trick," said Brenda, as she got up to set another place at the table.
That almost broke me again. I thought back to the empty refrigerator and cabinets at my place. That didn't last long though, since a minute later, Peter offered his hand to me to help me stand up, which I took with a much grace as I could muster. At least I didn't feel underdressed, since I hadn't changed clothes from my outfit I wore to work.
I sat down at the table, and the small talk began. They skirted around the delicate subjects, but a few times, I became moody. It seemed that they knew when I was about to break down. Dinner continued, and afterwards, I helped Andrea and Brenda clean up. Then we were all back in the living room.
It was a cozy living room; the furniture was bulky but not too soft. I let myself rest on the couch. I began to try to think of a way to see if I could stay overnight, since I didn't have a bed at home and thought that it would be better if I went back to my apartment tomorrow after getting some sleep. While I was sitting there thinking, I guess time had flown and my name was called, most likely more than once.
"Diane, what are you thinking?" Andrea asked.
"Oh, just that my life is a mess, and I don't know what to do to get it back in order." I said, my tone low, but audible to everyone there.
"Diane, why don't you stay here tonight? Actually, I insist." She was almost reading my mind. Well that shouldn't be surprising, since she and I have been friends for what seemed like ages.
"I was just trying to figure out a way of asking you about that. Reading my mind again?" I said with almost a smile.
"You know you don't even need to ask." Andrea said.
"Actually, it was my idea." Brenda said.
I just looked at her. Brenda hardly every took the initiative, but it seemed that she was very annoyed with Andrea for not offering right away.
"I think that I will just set up one of the spare bedrooms now." Brenda then hustled up the stairs.
I just sat there, relieved that I didn't have to go home that night. I looked outside, and the sun had just started to go down. I looked at the clock. I couldn't believe it; I had been here for just a little over an hour. It seemed like an eternity. I looked around and decided to try to be part of the conversation.
Brad was talking about something to do with his office, and then he turned his head to look at me. "So what do you do for a living?" He asked.
"I work at a book store near my apartment. I just had three exhausting days there, and thankfully I have tomorrow off." Thinking of work got me depressed again, since I made so little there. The tears started to roll down my cheeks once again.
Andrea had left the room for a moment, and I just sat there, until Brad got up and put his arm around my shoulders. Peter got the tissue box and sat on the other side of me. What happened next, I could barely believe. Brad kissed me. Not on the lips, but on the cheek, but still, a kiss is a kiss. He was cradling me, and I guess he was trying to get me to stop crying. I felt like such a baby at that point. I looked up, and saw Brad and Peter looking at each other, Peter nodded his head, and Brad smiled. Peter got up, and went to talk to Andrea in the hallway. I don't know what was said, but Andrea seemed to have a very happy note in her voice. Andrea then ran upstairs, I could hear the muffled voices of Andrea and Brenda talking, and then a flurry of activity was happening upstairs. I didn't think it took that much to get the spare bedroom ready for my use.
During that time Brad came back into the living room and took his position next to me again. Peter then shifted to be next to Brad. They engaged me in more small talk, and I was getting tired of talking. All I wanted to do was find a nice small hole to crawl into. I tried to keep my voice from becoming hysterical. Then Andrea and Brenda came back down.
I looked up to see them walking down the stairs in some very alluring outfits. They sat down where Brad and Peter had been, and the two men left the room, going upstairs, a bit more sedately, but with some excitement just the same. Another flurry of activity, and they came back downstairs and were wearing more comfortable outfits, yet the clothes were more revealing and a bit showy. I also noticed that the men seemed to have lost the underwear lines. I took a closer look at my female friends, and their panty-lines seemed to have vanished as well.
Silently, they all helped me stand up, since I was not quite myself just yet, and they led me upstairs to the bathroom. Slowly the women stripped me as the men were drawing a bath for me. Brad grabbed a few towels, and Peter was sniffing the aromas of the bottles by the tub. The bathroom was huge compared to normal bathrooms. The tub was accessible from both sides with a separate shower stall. Peter was filling the tub, adding a drop from one bottle and a liberal dose from another. The room started to smell like a misty forest.
After I was stripped down, Andrea and Brenda lead me over to the tub, one on either side of me holding my arms out as if I were a queen. They deftly got me into the tub and slowly helped me lower into the water. The water felt heavenly, just the right temperature to help calm my nerves. Peter and Brad folded towels under their knees as did Andrea and Brenda. The men were kneeling at the foot of the bath and the ladies in the middle. They started to bathe me making sure not to miss a spot. They rubbed oils into my skin and washed my hair. They gave me the royal treatment to say the least. I was feeling relaxed and nearly calm, though my mind was not totally at peace, they were helping me forget the bad things that had happened to me.
After they were done bathing me, they helped me out of the bathtub and lead me to the shower to rinse off. Andrea stepped in behind me to make sure I had gotten all of the shampoo out of my hair and made sure that my body was totally rinsed off.
That aroused me a bit. Her hands touched my breasts, hips, and inner thighs. She gently made sure that even my pubic hair had no more soap in it. Her touches were erotic, but at the same time soothing.
Andrea and I stepped out of the shower and the men started to dry me off while Brenda was doing the same for Andrea. They were very gentle with the towels and seemed to be enjoying themselves immensely. The feel of the soft towels on my body added to my arousal. I could not believe what was going on.
I was still feeling worthless. My life was a mess, yet these people were making such a fuss over me that I could not help to feel somewhat awkward. My limbs were starting to loosen up, and I tried to relax even more. It felt dreamy.
After I was dried off, Brenda and Andrea fussed with my hair. It is long, and they took great pains to get the mass up off of my shoulders and out of the way. By the time they were done, my hair was in a bun, but it was comfortable not being tight to my head.
After that they lead me, naked, to the ladies' bedroom. I had been in the room before, but the bed was a new addition. It was massive to say the least. I have had a queen-sized bed before, but that bed out did a king sized bed. I dimly wondered where they had to go to buy the sheets for it. The bed was also close to the floor. It was only a single step up onto the bed. In my bemused state, I thought that no one could roll out of the bed and be hurt.
The men guided me to the bed with the women standing on it. The ladies guided me onto the bed. They gently turned me around and helped me sit down. Andrea sat down behind me, enveloping me in her arms. I leaned back into her, something that I hadn't done in a year. It felt good to be back in the arms of my friend, it felt safe. I put my head back onto her shoulder, closing my eyes, savoring her closeness. I felt my legs being massaged by two sets of hands, I could tell that the hands belonged to Peter and Brad. The hands were easing my muscles even more, while they were slowly spreading them apart.
My breasts were being gently rubbed, during this time, by very feminine and very familiar hands. Andrea had taken advantage of her position to make my nipples start to stand out. I felt a body straddle mine, and then a mouth on one breast. I opened my eyes in a small slit to see Brenda sucking on that breast. Andrea leaned back some more, and I with her. My arousal was building.
The massage on one of my legs stopped. I felt a definite male body kneel between them. I felt softly probing fingers touch my nether lips. Those fingers gently opened them up, and one traced around my clit, while another was tracing the outline of my opening. That is when I arched my back, took a deep breath, and started to moan.
The activity around my breasts started to become more frenzied. Brenda went from one breast to another, while Andrea kissed and nibbled my neck and shoulders. My breasts were getting a royal treatment. They were enlarging; the nipples were nearly half an inch long and were nearly red. I quivered with every touch to them. Andrea was keeping my head from thrashing about with her own. Brenda's lips and teeth worked even more magic on my breasts, and every once few moments I felt a light nibble on my neck or earlobes.
The hands that were on my nether region became more frantic. Sitting as I was, with Andrea behind me and Brenda in front of me, I could not tell which man was fingering me. He started to rub harder on my clit; I felt it enlarge. Another finger slowly, ever so slowly entered my cunt. I moaned louder, wanting it further down inside of me. I got no relief. Then the finger on my clit was removed. I gasped in frustration, but that was short lived. I felt the hot breath of him over my clit. I tried to lift my hips to meet that mouth. It got closer and closer, the breathing got hotter and hotter. I felt his tongue on my clit, when the breathing got very hot. It flicked out at my clit, as if like a whip. It was there then it wasn't. This happened over and over again. Then, when I though I could stand it no longer, my whole clit was enclosed in that mouth. I did scream that time. I was silenced with a deep and passionate kiss.
My whole body felt like it was going to explode with passion. I felt Brenda move off of me, I was able to look down and saw that it was Brad between my legs, and between his legs was Peter. I could not believe what I was seeing. The look on Brad's face was of extreme arousal kept under control. I sat there and watched Brad's butt quiver as a pair of hands griped it firmly. I watched entranced, with Brad sucking on my clit, and Peter sucking Brad's dick, just out of my view. I then looked at the hands on my breasts that were just recently being sucked on. I let out little moans, as I got used to that level of excitement.
I think that Brad noticed that I was calming down, so in one quick motion, he thrust two fingers right up my cunt. At the same time, Andrea squeezed my already enlarged nipples between her fingers. I screamed.
That was the moment that Brenda quickly took Andrea's place, so that Andrea could straddle me, lick me, and suck on my breasts. My breasts were so tender, so aroused, that even Andrea's breath close to them kept me aroused.
I was so aroused, so sensitive, that even the merest touch anywhere on my body at that point took me to a new level of pleasure.
Brad continued to suck my clit, while wiggling his fingers inside of me. He slipped another inside of me, but I was getting so tight that my vaginal canal was full with his fingers. With Andrea sitting astride me, I could not see what was going on with Peter, but thinking about him sucking on Brad's dick made me even more aroused.
I moaned louder and louder, wanting more and more. It seemed that they were willing to give it to me.
All of a sudden, it all stopped.
Brenda slid out from behind me, and her and Andrea gently laid me on the bed.
Andrea whispered in my ear.
"Let's let Brad fuck you now, you seem ready for it now."
I just nodded, and Brad kissed my clit just one more time, as he slowly kissed up my body. He kissed my stomach, between my breasts, and then placed one single kiss on both of them. Very slowly, he lowered himself onto me, and then with the same deliberate slowness, he inserted his penis inside of me. He did not immediately move, and when I tried to move my hips, I felt hands restraining me. It was torture.
I looked over his shoulder, and then I saw why he wasn't moving just yet. Peter was rubbing gel all over Brad's butt, and generously gelling his anus. I saw Peter cautiously lowering himself on top of Brad and me. Brad shuddered as Peter's penis slowly disappeared in Brad's ass. Brad then began to move. He slid his penis slowly out of me, and made Peter's penis sink into him. The pace slowly built up. On one side of me, I saw Andrea and Brenda making love to each other. As I watched that, Brad slid himself in and out of me. All of a sudden, Brad slammed into me hard. I gasped. After that, he was frantic. He pumped in and out of me faster and faster, which meant that Peter was slamming into him that much faster as well.
I wanted to moan and scream, and I did. My whole body was tensing up. I felt my orgasm rising in me. I grabbed for Brad's ass, but I could not get a grip. I flung my arms out and felt one hand on a breast. I started to squeeze it, not caring who it belonged to. The person did not seem to mind. I felt the sweat running down my body, I felt Brad's sweat on my body as well. I felt Brad shudder, seeming to want to control his orgasm, but I did not let him, for at that moment, I came. My first orgasm brought Brad to his, and as I felt him cum, I felt him trust into me, and the weight of both men crashed into my body. I had my second orgasm right then. I came and came and came. I didn't think that the spasms would ever end.
As slowly as Peter entered Brad, he retreated. Brad shuddered again, and with that shudder, I had another orgasm. Brad's penis started to go limp inside of me at that point. Brad laid on top of me for a second or two, letting his flaccid penis fall out of me. He kissed me gently on the lips, and then he rolled off of me into Peter's arms. I was not left alone for long. Andrea and Brenda rolled over, after they had regained their breath and held onto me while I shuddered with more orgasms. I didn't think that I could orgasm that much.
Andrea and Brenda cuddled close to me running their fingers lightly over my skin, cooing to me. I was exhausted.
The men got off of the bed, and Brad leaned over and kissed once more before leaving the room with Peter. Andrea and Brenda helped me sit up, and then got me to the shower again, so that I could rinse my sweaty body off. Then the two of them cleaned up as well. I was handed a robe and my panties, and they lead me downstairs to the living room. The men were sitting there, both looking as tired as I felt.
"Brad, Peter, you two can have the other room tonight, I don't want you to have to drive home." Brenda said.
"Thanks." was all Brad said. He looked wiped.
I just sat there, looking at my lovers. I genuinely smiled at them for the first time that night.
"You were all wonderful, I just want you to know that." I said tiredly. "Next time, let's make it one on one, the four of you are a bit much for me to handle." I laughed then. I felt happy and the love of friends. It made the whole day brighter. I felt like I could face the world again.
After a while when we had gathered the strength to go up the stairs, we went to bed for the night. Andrea and Brenda retired to their room, and Brad and Peter retreated to the other spare room, leaving me alone in my room. I didn't mind at all. That was just too much for me, and I felt a little overloaded. I slept like a baby.
hr
Diane never went back to the apartment. Brad and Andrea went over to pack up her things; she had so little it only took one trip with both of their cars. Brenda, meanwhile, talked with the rental office to clear up any legal troubles. It was helpful that Brenda was a lawyer. She made it clear that since Diane had not been on the original lease that she never signed any agreement to lease the apartment in the first place. The apartment complex went after her ex for the money for breaking the lease and kept the security deposit.
Peter stayed at the house with Diane to keep her company, since she woke up feeling down. When everyone was back, they had a big lunch, and the men went back home.
The guys ended up moving in about two months later.
Whenever Diane brought home a date, the introductions were sometimes complicated, and most men that she bought over were never heard from again. Diane didn't mind that much since she was looking for an open-minded man, but the others in the house never let her be truly alone. Everyone seemed to know who needed what when.
Diane was able to save money and was hoping to get a new place sometime, but it didn't look like it was going to be soon. Her job was still being stingy with her pay.
hr
However, things only got better...
2 Between the Stacks
I normally work odd hours, unlike my roommates. Brenda's a lawyer, Brad's a financial consultant, Peter's a beauty consultant, and Andrea's an interior decorator. I work at a bookstore. It is a small one, owned and operated by none other than the mayor. It is a small town.
It had been a particularly busy night with all of the schools sending kids home with book lists, including the college kids. It was a Friday night which made it even more hectic. I was straightening up the shelves, while Andrew, the owner's son, was closing up the registers and getting the paperwork in order.
It was quiet in the store that night after closing. Even the street outside was quiet. I was reaching for an upper shelf when I felt him behind me.
"Let me get that for you, Diane."
I smiled back at him.
"Thanks."
I moved out of the way so that he could get the book where it belonged. My butt brushed up against his groin, and I felt the stirrings of an erection in his pants. I was amused by that and stifled a giggle. He seemed to notice though. He looked at me and smiled.
"What are you doing after work?" he asked.
"I think I am just going to go home and try to get some sleep. Tomorrow is going to be rough if today is any indication of how this weekend will turn out."
"Sounds good." he replied.
He was inching closer to me. His eyes were bright with just a hint of playfulness in them. I smiled back at him.
"I have to tell dad that the cameras are on the fritz again."
"On the fritz? I didn't even notice that they weren't working." I said looking up at them.
"Well, it happens now and again, but this is the first time that they stopped recording."
For some reason, that didn't sound possible, and I got the subtle hint.
"The tape may have just run out, and you need a new one." I said, my voice carrying my meaning.
"That is what I think it is too. I need to get a new one, and put it in the VCR tomorrow."
"Sounds like a very good idea, since we will probably have more kids in here than tonight, all day even. I just wish the schools would provide those kids with the books, not that the business isn't good for the store. I just feel sorry for the parents." I smirked.
Suddenly his tone changed, and I felt his breath hot across my ear.
"Tell me to go away, please, or I may just do something I might regret. I won't be able to restrain myself, it has been so long for me."
It was a plea, a scream for me to stop him from letting his lust emerge from its cocoon.
"There would be regret?" I asked quietly.
"I am not sure, but if you don't say no, I can not guarantee anything later." His voice carried his lust, his brute desire.
"I can't say that."
With him standing so close behind me, I felt his prick stiffen though his pants and my skirt.
As we had done in the past, most of the lights were off so that the store looked closed, so no one would walk up thinking it was open.
He threw his arms around my waist as soon as the words were out of my mouth. He pressed his hard prick against my rear, and started to rub himself on me. His hands crept up the front of my blouse, and he grabbed my breasts through my shirt. I had to put my hands on the shelf to keep myself standing still as he gyrated behind me. His hands moved slightly, rubbing my breasts, and his prick was so hard on my ass. I put one hand in front of me, and put my forehead on it. With the other hand, I moved it so that I could grab his hip. That gave him the clue he needed.
His hands worked on the buttons of my blouse. I felt his fingertips brushing heavily on my bare skin. For some reason, I had worn my strapless bra to work that night, and at that moment, I couldn't remember why. He pressed me so close to the bookshelf that I was glad that it was a shelf, since a solid wall didn't allow the same access.
When my blouse was completely unbuttoned, he felt for my bra. He held my encased breasts and just squeezed them. The bra was not that thick. My nipples hardened, and my breasts themselves grew larger. He pushed my bra down and started to rub my, now, bare breasts. That sent me through the roof. I started to rub my ass on his prick. I couldn't help myself. With my free hand, I lifted my skirt up and over my butt so that there was more, closer contact. That sent a shiver through him.
With my hair up in a bun, he had easy access to my neck. He leaned over and kissed it. Then the kissing became nibbling. The nibbling ran from one side of my neck to the other and down my shoulders. He nibbled from one shoulder to the other, back and forth. I was getting light headed by this time.
His hands slowly lowered from my breasts, down over my stomach, to the waistband of my skirt. He felt around it and found the button in the back. He rubbed my ass at that point and then he unbuttoned my skirt. It slid to the floor easily. I don't think he was prepared for me to be wearing a very sexy garter belt. I had found that full nylons were just too much, so a garter belt was the only option I had to keep within the dress code.
When his hands felt my bare thighs, I could almost swear that his heart skipped a beat. I know that my heart was pounding. He slid his hands under the thin cloth of my panties to feel my ass. I nearly collapsed. He slid his hands around to my front while they were still under my panties. I felt him run his fingers through my pubic hairs, and he ran one finger down over my clit. I nearly jumped, since I was already very aroused. I spread my legs a bit, so that he could do more, and he took my lead.
He took my clit between two fingers and gently squeezed it. He just held it like that for a while before letting his fingers slide down any further. When his probing fingers found my vaginal hole, they plunged right in. There was little resistance, since I knew that I was already wet. I gasped and started to moan. I had to use both hands to support myself so I could stay upright.
I felt him pressing against me again. His dick strained against its confinement. I tried to use one hand to undo his pants but the position was wrong. He did it for me. His pants slid to the floor, after a little bit of wriggling, which sent me even higher, since his fingers were still inside of me. At that point all that was between us were two layers of fabric, but his dick was so hard that it was poking out of the opening in the front of his underwear. That only left one layer, and that soon disappeared. He unclasped the hooks on my garter belt, and slid my panties down my thighs. He wiggled again; I knew that his underwear was now on the floor too.
His breath was ragged, and I finally felt his prick on my bare ass. He just rubbed it between my ass cheeks for a while, while he continued to rub my clit with his thumb and he wiggled his fingers inside of me.
He took his fingers out of me and held me close for a few minutes, taking in our closeness. He pulled me backwards at one point and leaned up against another shelf, on one of the vertical dividers. He put his legs between mine and gently bent me over. He fingered me again and kissed the middle of my back.
Then I felt his dick slide towards my vagina from my backside. I positioned myself to receive it, and it slid in so fast and easily, it was in me to the hilt before I realized it. I nearly let out a scream. I just stood there a moment, before he started to push me forward on his dick. He then pulled me back hard. I was filled once again. After that it was nearly a blur. He would push my hips forward and back, hard and fast. I could barely keep my breath. I don't know how long this went on, but it felt like ages.
I heard him yell out, and that made me tense up. I had thought he was going fast during, but he sped up so much, that my orgasm also was near, and my moans were getting louder, as were his. Then he stopped, and I felt the liquid warmth of cum spread inside of me. I then let out a scream and had my first orgasm. He kept on squirting his cum inside of me, while I kept on squeezing it out of him. He held me there tightly, his hands on my hips, his fingers digging into my flesh.
I felt him shudder with a final release, and his hands moved slowly up my front to my breasts. He gave them a gentle rub before helping me stand upright. He gave me a short backrub to get the kinks out. I straightened up and shot a smile back at him over my shoulder.
"Was that so bad, Andrew?" I said.
"No, Diane, that was great, and you are just so sexy right now." He had a tired grin on his face, but there seemed to be a hesitation in his eyes.
"You look happy and worried at the same time." I was genuinely concerned. I was not afraid for my job, just what this will do to him.
"I am worried. I don't think that we could work together again without me wanting you again."
"Andrew, you can have me anytime you like, for now."
"I am not so sure if we should do this again. We will have to see. I think we had best clean up a little and get out of here." After saying that, he picked up his clothes off the floor and headed to the back room where the bathroom was. He went in and cleaned himself up, and then I did the same.
As I walked past the area that he and I screwed in and looked at the sign for the section. Ironically, it was the Sex section of the store. I grinned as we walked out of the store and he locked it up for the night.
"See you tomorrow Andrew." I said as I jumped into my car.
"I won't forget this, Diane, ever." He said as he slid into his car.
I smiled as I drove away.
hr
Diane kept working at the store, as did Andrew. They kept their relationship for a few weeks, until Andrew moved away, and she took over managing the store for Andrew's dad. His dad never suspected what happened in the store that one night, but every time that Diane walks past the Sex section, she smiles.
2 The Peak
It had been a hectic day at work. I was still learning my managerial responsibilities. There was just so much I had to know and even more to do than I realized. I was bone tired as I climbed the stairs. Everyone seemed to be out for the night, which was not so strange for a Saturday. I got to my room, stripped off my clothes, grabbed a robe, and headed for a shower. I was seriously considering a bath instead. I got to the bathroom, and that clinched it, a quick shower and then a nice relaxing bath.
I sat in the bathtub for quite a while letting the water calm my nerves. I started to think about the job again, and how much I wish Andrew had stayed, but he had become a partner in a business out of town so he had to move. I was stuck in the store as manager. Tonight was just one of those nights from hell. The money was off by ten dollars, which with a store as small as mine, well the mayor's, ten was a lot. It was bound to happen, since the new girl didn't seem to be catching on to quickly.
We hadn't been too swamped, thank goodness. That was the only saving grace. Finding the check under the register helped. That has left us only five cents short, so I threw in the nickel. All in all, not too bad of a day, it was just a very busy one.
I had let myself float in the tub for I don't know how long, until a voice brought me back to reality.
"Hey, you going for the prune look, Hon?" Andrea said as she looked down at me, sitting on the ledge of the tub.
"Oh, I must have dozed off. How long have you been home?" I asked kind of groggily.
"Long enough to know that you were turning into a prune, and for Brenda to make something to eat. You coming?"
"I'll be down in a minute. What's she making?" I was already starting to stand up.
"Oh, probably something complicated and will probably use every pot we have." She and I groaned together.
"Hand me a towel, would you?" I said before Andrea could vanish.
She threw one at me.
"The guys should be home any minute now, and then we can eat." She slid out of the room.
I got out of the tub, dried off, and put my robe back on. I went to my room to get something on for dinner. Dinner is not usually a formal affair, but the rules of the house are, come to dinner dressed. Breakfast was the only time of the day when any of us would come down in our robes or just undies, but that was okay, since none of us really care that early in the morning.
I got downstairs just as the guys arrived home.
"Brad, Peter, get freshened up and get back down here, dinner is almost done," was the yell from the kitchen. They both smiled and jogged up the stairs.
I went in the dinning room, grabbed the plates, and started to set the table. Andrea joined me.
"Well, at least you aren't a prune." She laughed.
"Diane, the next time you take a bath, set an alarm clock or something." Brenda said from the kitchen. That she didn't come out of the kitchen was a sure sign that she was making one of her big dinners. At least she could cook, Peter never got the hang of it, and the rest of us are mediocre at best.
After we ate, Brenda and Andrea told us that they were going back out again, and that they would be gone the rest of the night, and asked if Peter or Brad would clean up. I guess I looked as bad as I felt. I just sat there looking off in the middle of the table. Brad shook my shoulder to get my attention.
"Hey, why don't you watch TV for a while, at least until we get done cleaning up in here, okay?"
I nodded and slid my chair out from under the table. I got up stiffly and walked to the living room. I looked at the TV Guide and saw that nothing was on, so I picked out a video to watch. I sat there staring at the screen for a while, but with dinner in my stomach, it was beginning to make me feel better. I was more awake at least. I looked towards the kitchen and noticed that the guys were nowhere to be seen. I shrugged and decided that they went to bed.
When the movie ended, I got up and went upstairs to go to bed. At least I had the energy to walk up the steps. The last time I fell asleep on the couch I had woken with a stiff neck. That got chuckles from the guys, and Brenda smirked. Andrea was to busy rubbing the tension out.
I got to the top of the stairs and went down the hall to my room when I got a glimpse of the guys through the slightly open door. I was mesmerized. I had never watched them, nor had I ever thought of it, but I just couldn't move away.
I slowly slid down the opposite wall and sat on the floor. I had worn a day dress to dinner, and with the rush, I hadn't put anything on underneath. I got into a comfortable position and looked in at them together.
Brad was sucking on Peter's dick. I had never seen this before. I knew what was going on that first night together, but Brad was on me, so I never fully realized just how versatile Brad was. I saw Brad's mouth going faster and faster on Peter's dick. I knew how a dick felt in my mouth, and how it felt inside of me, and watching them together aroused me like crazy. I wanted to rush in there and suck on Brad, but lately Brad and Peter have been having some problems, so I controlled myself to a point.
As Brad swallowed Peter, I put my finger in my mouth and sucked on it in the same rhythm that Brad was on Peter. I could not believe that they didn't see me, but I couldn't move. Then I saw Peter reach down and stroke Brad's shoulders, and gently pull his face off of his dick. Peter turned Brad around and stared to rub his dick all over Brad's ass. I let my finger drop to my cunt and rubbed my clit.
Then Peter turned Brad around, he went down on Brad. I continued to play with my clit while Peter sucked on Brad. I didn't know how long this went on, but I was rubbing myself so hard that I felt that I was going to burst. I tried to stay with their rhythm and did, faithfully. I wanted this to last as long as they did.
They went into a 69 position, and I put one finger in my mouth as my other hand played on my clit. I just went crazy but stayed quiet. I usually masturbated quietly, so this wasn't a problem.
My clit was sore, and my cunt was screaming for me to release, but I had to hold on, had to make it last, so I changed speeds, and started to play with my nipples through the dress. They got hard rather quickly, and I rubbed them while I watched the guys sucking on each other, and the slurping and sucking sounds just aroused me more.
My eyes took all of this in, and I just wanted to see them fuck each other. I didn't have to wait long. Brad pushed Peter off of him, turned him over, and started to gel up his butt. I knew what was going to happen next, and I waited, my finger right over my cunt, while Brad continued to rub Peter's ass. I put my hands on my butt, where it wasn't on the floor, and let myself envision Brad doing that to me. I could hear Peter's moans, and Brad's quick breathing. Then as if lightning had struck, Brad was buried inside of Peter to the hilt. I was amazed how fast it went in. I put my finger inside of my cunt, while pressing my clit with my other hand. I kept the pace that Brad was setting, and hoped that I could last through the entire sexual act. I kept rubbing my clit and shoving my finger deeper and deeper inside of me. I added another finger after that and just kept going as fast as Brad was going inside of Peter. I could hear both of them panting and moaning. I wanted to join their chorus but knew I couldn't.
I heard Peter scream first and saw him arch his back as I saw the waves of pleasure going up his belly. I watched, hoping that they would have their eyes closed, which they fortunately did. I heard Brad a few seconds later scream his pleasure, and I came with him. My fingers were dripping with my juices, and I saw that Brad and Peter were dripping juices themselves.
When my body was calm enough, I slowly got up from the floor and went to my room. I shut the door quietly, but not all the way. I didn't want them to hear the door latch. I lay down in bed and tried to go to sleep. My body was still trembling from my orgasms, and I hoped that neither of them would check to see if they woke me. I turned on my side, and just laid my hand on my clit and the other on my breast, gently stroking each. My body wanted more, I knew that, but right now, I knew that I wasn't going to get it.
I heard them cleaning up, so I grabbed my vibrator, put it inside of me, and turned it on low. I had a few more orgasms, then my body was then spent completely, and I drifted off to sleep.
hr
Diane never said a word to the guys, and they never even hinted that they knew. The household continues with no major upsets for a few months. Then a tragedy struck...
