#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib '../../files/lib';
use Base::HTML qw(html story);

html( code => sub { story(*DATA) });

__DATA__
Listening to Nick and Joe talk about what they'd do to a sexy avatar in their video game got Zoe thinking about how much she wanted to have sex. The guys weren't exactly her type, and they'd been living together for three years without sex entering the picture. For the last seven months, Zoe was in the middle of a dry spell. She couldn't get laid to save her sanity. Listening to them talking about sex in the living room made her take a really good look at Nick and Joe from the entry to the hallway which lead to their rooms. They were so oblivious at this point, they didn't notice her looking at them with a more serious expression than she had ever used on them before now.
Zoe met Nick and Joe when she was dating Rob. The three guys would get together at a video game store to play the newest games with other gamers every Tuesday and Thursday. Zoe didn't mind Rob's interest in games, except when she really needed to talk to him one night about going to her cousin's wedding and the next rent payment. When she snatched Rob's game controller out of his hands that Thursday three years ago, he slapped her hard across her face. Tony, the store owner, saw the slap; and all of the other gamers heard the slap and looked up to see Zoe crying. Tony rushed to Zoe immediately.
"Are you okay?" Tony asked with concern in his voice and eyes.
All Zoe could do was shake her head "no" and cry. Nick and Joe were close enough to Rob to grab him.
"I'm calling the cops, asshole." Tony told Rob with no pity in his voice. "Zoe, you're starting to bruise just a bit, I'd like to snap a picture to show the cops when they get here."
Zoe nodded still shaken by Rob's outburst of anger. She couldn't stop crying, not just from the slap, but also knowing she had probably just lost her first apartment. She couldn't make the rent alone. Tony got her to sit down to wait for the cops who were called by Janice, Tony's wife and partner. Nick and Joe were still holding Rob when the police arrived several minutes later.
"You are pressing charges, right Zoe?" Janice asked while the police were walking through the door to the shop.
"Yes." Zoe whispered as she wiped away the tears with a damp paper towel Janice brought her. Janice stayed with Zoe while the police asked her a few questions. She looked up to see Rob with his hands behind his back and a tall skinny police officer holding him in place. Rob had a lot to say about the police and Zoe as he was being dragged away to the police car. The short older police officer, PO Randy Jarvin, handed her a piece of paper with his card.
After Rob was taken away, Tony and Janice restored order to their shop.
"Okay people, excitement over, you can go back to your games now." Tony said waving his hand towards the various computer and television screens. Most of them went back to playing; but Nick, Joe, and a few others couldn't get back to their games after what they had just been through. The few women who played all stepped away from their games to sit quietly with Zoe in the back of the store.
Janice came over a few minutes later and handed Zoe a $50 gift card to the store.
"Oh, Janice. I know it wasn't your fault, why the gift card?"
"Zoe, you might not be a customer here, but of all of the girlfriends I've seen guys bring into the store, you are the most welcome. You know, I've never heard you complain about Rob's time here, ever, except for tonight. So come back anytime you want."
After a few weeks and Rob's incarceration, Zoe came back to use the gift card. Nick and Joe were there playing a rather simple game, far easier than what she usually saw them playing. Out of habit she sat in the chair which once was next to Rob's normal chair. With Rob gone Nick switched seats since it had the better view of the screen they normally used for their games.
When Zoe sat down, Nick and Joe noticed right away. They turned their heads and nodded to her rather quickly, then turned their heads back to the game. She watched for a few moments, and those moments were all it took for the guys' characters to get killed in a spectacular manner.
"How are you Zoe?" Joe asked after tossing his controller aside.
"I'm okay, though I'm getting ready to pack up the apartment and move back in with my parents. Without Rob I can't afford the rent. If I don't come up with this month's rent in a week, I'm getting evicted."
Nick and Joe glanced at each other and brightened a little.
"What if you can come up with the rent by the end of the week, would you still move out?" asked Nick.
"I don't see how I can, the rent is $1,500 a month, and I only have $950 of it. I tried getting an advance from work, but with money so tight everywhere, they can't afford to pay me early."
"Well, Nick and I are looking for a place, and if you have a spare room, would you consider letting us move in with you?" asked Joe with a hopeful smile.
"The apartment is awfully tiny, and there are only two bedrooms. I guess I could move into the smaller one and let you share the bigger one. Why do you need a new place?"
"My apartment building got condemned so I'm staying with my brother and his wife until I find somewhere else." said Nick with a hint of anger in his voice.
"I'm one of those lame guys who still lives with his parents." said Joe dejectedly.
"Well, I'm going home now. You want to come over and look at the place? I really don't want to live with my parents again. They are nice enough, but I can't face them right now. They never liked Rob, and now I know why. But, I came here to talk to Tony, so if you'll give me a couple of minutes, we can go back to the apartment after."
Both men nodded and looked a little excited which worried Zoe a little bit. So, when she talked to Tony about giving back the gift card she'd never use, she also asked about Nick and Joe. Tony told her they were excellent customers who never caused any trouble. When he asked why she was asking, she told him about the possible future living arrangements. He warned her to be cautious, but he saw no immediate reason not to trust Nick and Joe.
Right after they left the shop and arrived at her place within fifteen minutes. The rooms weren't as small as they feared with the "master" bedroom being large enough for two twin beds and two smallish dressers. The room Zoe would move into looked just big enough for the double mattress which appeared to be on a simple bed frame. They talked over the living arrangements for a couple of hours, and the guys even helped her get moved into the smaller room. Even with Rob's belongings gone, it was a tight fit. To her surprise the guys pulled out their phones and transferred their rent and utility money to her before they left.
Over the years Zoe learned just how deceiving looks can be. There were times when the clothes Nick or Joe was wearing looked like they needed washing or worse burning; but if she got up close, she could smell the fabric softener. She had to get used to a mirror over the kitchen sink because while one guy was shaving in the bathroom, the other was shaving over the kitchen sink. They did make sure the clipped hair from their faces never got into the coffee pot. Both left the apartment whenever she decided to wax her legs; her little yips as she pulled the hair off of her legs got to them the very first time she did it.
While they were living together, they all got little raises here and there, and Joe got a real promotion. When the guys could afford it, they started buying gaming equipment so they could play in the apartment instead of going to Tony's. Zoe had to put her foot down when their game play drained the bandwidth of her internet connection. They all dated but no serious relationships yet. The guys were very fastidious about getting the rent and utilities paid on time.
Tonight was the first time Zoe had ever looked at her roommates of three years as potential sexual partners. Since they had a lingering connection to Rob, she hadn't noticed how good looking they were; even when they sat in the common room in t-shirts and boxers playing video games. It took the guys only a few months to get comfortable around her enough to walk around the apartment in only their underwear. Neither of them had made any advances on her because it was one of the first issues they discussed the night before they moved into the apartment. Neither would hit on her unless she hit on one of them first. With how Rob treated her several night's prior to them moving in, Nick and Joe were willing to give her a wide berth.
Listening to their conversation about the sexy avatar on the television screen caused her to get horny. She recognized the game they were playing and knew they weren't very far into it, meaning they would be playing for the next several hours. Zoe wondered if the woman playing the character Nick and Joe were salivating over knew what effect her character had on them. Zoe quietly snickered and knew the player at the other end probably knew exactly what the sexy avatar did to men who played the game.
As Zoe thought about their time living together, Nick and Joe had become more appealing by the second. Even though they loved playing video games, it didn't mean they lived unhealthy. They both had flat and firm abdomens and really nice butts. They didn't have big muscles, but they were strong enough to carry furniture up two flights of stairs, since their building didn't have elevators. She'd also seen their early morning hard ons upon occasion.
Zoe quietly went into her bedroom and changed into something sexier. She put on a pair of sheer, mildly lacy, white panties with the matching sheer bra with only a thin fake satin robe over them. When she walked out into the common room, they were still playing the game seated far enough apart on the small couch, she could fit between them. Not to disturb their game play, she slid over the back of the couch and between them with ease. This wasn't the first time she watched them play, but it was the first time she decided she wanted to seduce them, though she had to take another moment to make sure she really wanted to do it. Looking back and forth at their faces, she knew she really did.
Nick and Joe didn't ignore Zoe's presence, they glanced over at her making eye contact for a brief moment, then they went back to playing their game. The conversation about the sexy avatar, which was still on the screen, ended when she joined them. She looked down at their laps, and the sexy avatar had a small affect on the guys. Even she got a little more excited as she watched the avatar's boobs jiggle on the screen. The player on the other end really knew how to make the most of a computer generated character.
At first Zoe let her hands fall to her thighs, then she let them slide between her and both her roommates thighs. As lightly and slowly as she could, she moved her hands to the front of their thighs. Neither guy noticed right away. She lightly slid her hands up their thighs to the point where her fingertips were almost touching their penises through their boxers. It took only a little wiggling of her fingers to open the slots in their boxers to see their penises, and she wasn't disappointed. She knew how engrossed they were when they played this game, so it didn't surprise her they were unaware of what she was doing. She watched the game on the screen and noted the movements of the guys' characters which gave her an idea.
At this point Zoe couldn't believe how much she could actually get away with while they were playing. She managed to get both of their penises through the slits in their boxers without them noticing, however, she thought they were about to advance to the next level, which meant they would be back in reality for at least a moment. She got a reprieve when she saw they were about to go into a sub level. She decided now would be the perfect time for her to get their attention. She wrapped her hands around Nick's and Joe's penises and gave each a gentle squeeze. They were so startled, their controllers fell onto their laps. A button on Joe's controller hit her knuckle on her left hand, which caused Joe's character to jump. When Zoe saw the jump, she moved her hand up and then back down Joe's penis. Nick's character was standing frozen on the screen, so her right hand stayed stationary on Nick's penis. Nick's penis throbbed.
"Zoe?" Nick and Joe asked in shocked unison.
"You play your game, and I'll play mine." she answered with a smile. She nodded toward the screen. They were being nudged by the other players to play the game.
Joe took a deep breath, and Nick quickly shook his head; then they began to play again. Zoe watched the action on the screen and mimicked the behavior of Nick's and Joe's characters. If they were just walking and doing nothing of note, her hands were stationary. When the characters ran, her hands began to move faster up and down their shafts. If the character jumped, she would give a little squeeze. When they fought, she would move her thumb over the tips of their penises, rubbing them as fast as their weapons were swishing on the screen.
As Nick and Joe progressed through the game, their characters' behavior got more erratic. The other players began sending text messages to stop fooling around. The rapt smiles on the guys faces told Zoe they did not want her to stop. In the next battle, Joe's character got stabbed. She leaned forward and placed a little kiss on the tip of Joe's penis. With one eye still on the screen, she noticed Nick's character get hit on the head, so she places another little kiss on the tip of Nick's penis. Each time their characters were hit, she would give another little kiss. As the fight drew to a close, it was game over for Nick's and Joe's characters. They were unable to concentrate on the game anymore. Nick's character got killed, which is when Zoe slid to the floor, turned around, and started to give Nick a blow job. She put her right hand around Joe's penis and kept massaging it. She licked and sucked Nick's penis while listening to the game. When she heard the death sound from Joe's character, she put her left hand around Nick's penis giving it a firm squeeze and wrapped her mouth around Joe's penis and began licking and sucking Joe. The guys tossed their controllers to the side and ignored the angry protests of the other players, even the sexy avatar.
Nick's and Joe's characters had additional lives, but they weren't being played at the moment. They guys were sitting back while Zoe kept massaging their penises with either her hands or her mouth. Nick threw aside his controller and slid her back onto the couch. Joe opened the front of her robe to reveal her very sexy lingerie. Joe slid his hand up to her left breast as Nick slid his hand to her right breast. They rubbed her breasts above the very thin fabric of her bra. Taking a very short break from rubbing her breasts, they pushed her forward slightly to slide her robe down her her arms then down her back. While Nick unclasped her bra from the front, Joe slid her robe completely out from under her and laid it on the arm of the couch. With her breasts free from their meager enclosure, they pushed her back onto the couch then leaned in to taste her breasts.
As horny as Nick and Joe were, they sucked on Zoe's breasts hard and licked them roughly. As one they lifted her butt off the couch so they could remove her panties. When her panties were on the floor, they parted her legs so they could get their hands between her thighs. Joe's fingers found her clit first, so Nick's fingers rubbed her on the inside. Joe rubbed her clit until it reached its full aroused length. When she moaned Nick wiggled his fingers faster inside of her. She reached out again, took hold of their penises, and began to rhythmically squeeze them every time they made her shudder.
"I'm not going to last much longer!" moaned Nick pulling his boxers off and throwing them to the side.
"Me neither." replied Joe also pulling his boxers off. "I have an idea."
Joe disengaged from Zoe for a few moments to get a tube of lubricant and a couple of condoms out of his small travel bag. While he was away, Nick took the opportunity to kneel between her legs and plant a kiss right on her clit. Nick licked and sucked on her clit making her moan louder than before. When Joe returned to the couch, his erection had slightly faded. Zoe motioned Joe to the back of the sofa, then she took his penis into her mouth and began sucking on it while Nick was nibbling, licking, and sucking on her. When Joe was back to full stiffness, he handed a condom to Nick. Both men rolled them on their very stiff penises with practiced ease.
When both men were protected, Nick and Joe took to Zoe's breasts again. This time however, Nick wrapped his arms around her and brought her to the floor facing and on top of him. With a very quick upward thrust, Nick was in her vagina. Zoe went to move, but she was held very still as Joe dripped cool lubricant between her butt cheeks. Zoe felt Joe's penis slowly entering her anus. When it was in as far as Joe would go, he gave a little push. Nick understood and released his hold on her. She began to gyrate her hips and felt both men's penises move inside of her. It wasn't long before her gyrations were accompanied by Nick's and Joe's independent thrusts.
It wasn't very coordinated and was somewhat awkward in the hour it took for them all to orgasm. When their bodies contracted with the spasms of orgasms; Zoe, Nick, and Joe moaned loudly and explosively. As Nick and Joe's penises returned to their normal sizes, Zoe was still shuddering from the orgasms she was having after theirs were over. For her taunting them during their game, the guys continued to play with her and keep her orgasming. Her breasts were bright red, her nipples hard as ball bearings, her clit could be seen extending beyond her nether lips, and vagina keep seeping vaginal fluids. They stopped when her breathing began to sound a little labored.
After they all took showers alone, they came back out to the common room. Nick and Joe could not stop staring at still naked Zoe, while Zoe could not stop looking back and forth between Nick and Joe. They were all speechless from what just happened. The men were confused. Nick cleared his throat and took a swig from his now lukewarm soda. He opened and closed his mouth several times, but no words came out.
"That was the most interesting way I've ever lost a character." was all Joe could think to say to break the spell.
Nick turned to Zoe and asked the very simple question, "Why?"
Zoe was too to tired to explain. She'd tell them tomorrow how they made her horny talking about about the sexy avatar. So all she said before she went to her room and fell into a satisfied sleep was "I thought you might like a new game controller." 
