#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib '../../files/lib';
use Base::HTML qw(html story);

html( code => sub { story(*DATA) });

__DATA__
Maya had a horrendous morning that lead to an even worse afternoon and her evening topped all of that. She had recently broken up with her very annoying quasi-boyfriend. He left in a huff which meant he had broken a few things as he left. She was feeling the loneliness creep up on her that night as she laid down in her empty bed. The slight chill of the sheets made her shudder until her body warmed them up. Since the break up she had a hard time getting to sleep which is why she put herself through hell that day. She wanted to be so tired that sleep would immediately fall upon her. It worked this time.
She slept deeply and well. When it came time to dream, she found her subconscious had her on a sandy beach. She looked around in all directions, but no water could be seen anywhere, which was odd for a beach. With her back to the sun, she saw three figures flying in from a distance. As they came closer, they were three very handsome men. When their feet touched the sand, they furled their wings and surrounded her. The first one came forward and winked at her as he stood to her left. The second one came forward, blinked, and stood to her right. When they were in position, the third one nodded as the first two grabbed her arms and slowly took what few clothes she was wearing off of her body.
She tried to get away, but these small men held her arms in a tight grip. She felt the fabric of her shirt slide across her breasts that were being bared to the light of the sun. The third man nodded again, turned, and gently flapped his wings just close enough for the tips of the feathers to touch her breasts. Her breath caught in her throat as her nipples began to harden. She swayed a little where she was standing when the nodding man turned and walked behind her. He grabbed the shirt's collar and began pulling it down her arms and back. When the sleeves bunched at her wrists, he took hold of the arm while either the winking man or blinking man removed the sleeves from her wrists.
Standing on the beach half naked, it was odd that she did not feel the heat nor sweat. Again the winking and blinking men took her wrists as the nodding man untied the knot from her pants' waistband. He did that so quickly, that the pants fell to the sand within seconds. He lifted one foot then the other to remove the pants from around her ankles. All she had left on was her panties which were quite ordinary. The nodding man once again turned his back to her and flapped his wings which returned her nipples' firmness. When he turned this time, she saw that her shirt and pants were neatly folded and laying on the sand.
With a nod from the nodding man, the winking man with his left hand and blinking man with his right hand slid those hands down each side of her body until they reached the backs of her knees. They lifted her up and into a horizontal position and laid her upon the sand. With her arms outstretched, they began covering them with sand. With each double handful of sand, the weight of that sand seemed to double until she could no longer move her arms. She began squirming as best as she could, but the nodding man stood at her feet. With the now familiar nod, the winking man and blinking man held down her legs while the nodding man slowly pulled her panties down to her ankles. They then moved their hands above her ankles so that the nodding man could finally remove that last of her clothing.
The beach sand was oddly comfortable on her naked body. The winking man bent her left leg up and to the left, and the nodding man buried her foot in the oddly heavy sand. The blinking man bent her right left up so that the nodding man could do the same to it. When she was firmly planted in the beach sand, she saw the three men smile. The winking man stayed to her left and knelt beside her, the blinking man stayed to her right and knelt down, and the nodding man stayed in the center kneeling between her legs. In unison the winking and blinking men bent over and took a nipple into their mouths. They had been losing their firmness, however, with this one action they perked up to a hardness they had yet to achieve. While they sucked on her nipples, their tongues slid over her aureoles. She had never had this much attention paid to her breasts ever in her life. With that small amount of attention, she felt moisture trickling from her, between her butt cheeks to the sand below, each drop causing her to feel odd sensations she had never known before.
The nodding man watched the winking and blinking men on her breasts and the flow of erotic juices coming from within her. The nodding man put out both hands and opened her lower lips and placed a single kiss on the flower within them. Though she could not move her arms nor lift up her feet, she arched her back with the sudden pleasure of that kiss. The men exchanged looks; winking, blinking, and nodding. They made her a narrow belt of sand so she could not move like that again. They arranged themselves as they were before and continued their kisses and caresses. She could not move much, only her head which she turned to look at each man with their mouths on her body. The flow of juices from her body increased. It was like the faster the juices flowed, the happier and more aggressive these men became.
They only gave her a small moment of rest every so often so she could catch her breath. They would turn around and fan her body with their wings. Each flap of those wings gently touched her skin keeping her continually aroused. Her breathing would return to near normal, and they would turn to begin again, though they would move around her in a counter clockwise move. Her nipples became larger and larger with all of the attention they were receiving. Her flower also budded outside the petals which would normally contain it. The nectar flowed from the small crevice that is under the flower down to the sand. When she could think, she wondered how much more would come out of her as the trickle became a torrent.
Then in one move, the winking and blinking men opened the petals and the nodding man placed two fingers from each hand inside of her opening her further. She felt the flood of juices flow from her vaginal opening, down through her butt cheeks into the sand. The sand was so moist that it began to form into a shape. At first she thought it was just the sand moving randomly under her, but she sensed something that felt like fingers massaging her lower back and butt. It was only when the three men who had been teasing her into sensual bliss stepped back that she knew something else was happening.
The sand between her legs began to form a head. That head was of normal size. The mouth opened and blew onto her already swollen genitalia. With a smile the head craned forward so that she could see the neck. The mouth came down and suckled on her more thoroughly than the three others had before. She could not help but to gush more. She then felt his shoulders then arms on her thighs. When his hands finally appeared, he seemed to be able to pull the rest of himself from the sand. He kissed up her belly, over her belly button, to the gap between her breasts. When he reached that point, he took one then the other into his mouth. She could feel his belly laying over her lower lips rubbing against the aching flower there. When her nipples were again at a proper firmness, he continued up her bust to her neck, kissing all the way. When his lips crested her chin, and his lips met hers, he lifted himself above her and with a sudden thrust, he was deeply inside of her.
It felt like a smooth yet yeilding glass rod was being thrust deep inside of her again and again. With a sudden strength, she freed her arms and wrapped them around this man made of sand as he pounded himself into her. She cried out in pleasure as her muscles contracted around him whenever he pounded deeply. She tried to find something on his back to grab hold of, but it was also smooth as glass. All she could do was place her wide open palms on his back. His lips were on hers again after what seemed like hours. With several even harder thrusts than there were before, it felt as if he shot his juices inside of her.
He then stood up and offered his hand to help her stand. At first she felt so dizzy, she did not think that she could stay steady. When she finally stood, he kissed her gently and with a smile.
"Thank you" he whispered as he quickly disintegrated back into the beach.
She looked around, and the winking, blinking, and nodding men could only be seen flying away. She woke up from her extremely intense dream and quickly turned on the light to find her clothes folded neatly and laying on top of the hamper. She lifted the sheets from her body to see her own nakedness. Between her legs and touching her lower lips, she found a large glass marble. She thought this just had to be more of the same dream. She looked at the clock, and it was time that she got out of bed for work.
That night she put the marble in a bowl on her nightstand. Again Wynken, Blynken, and Nod prepared her for the arrival of the Sandman.
