#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib '../../files/lib';
use Base::Page qw(page story);

page( 'code' => sub { story(*DATA) });

__DATA__
That day I went over to his house to meet with him for a wonderful evening of passion. I got there and knocked on the door. When he answered his eyes told me something was different. I got the feeling that he was hungry. I was a bit confused since he had never looked at me that way and was wondering if this was a good idea. I had the feeling of being prey.
I knew he was quick, but with speed I was not used to, he jerked me into the house and slammed the door. Before I had even gotten a chance to take off my jacket, he had his lips on mine, and he was kissing me roughly. My arms went around him for balance, but that didn't help, since he just pulled me further into the house after that first kiss.
I was looking at him, wondering what had gotten into him. I was able to get my jacket off at this point, but after that he was on me again. He unbuttoned and unzipped my jeans and had them down on the floor within seconds. He ran his other hand down the front of my shirt and had that unbuttoned and on the floor in less time then my jeans. I was shocked and surprised. He usually was slow and gentle, but today he was just the opposite. He pulled my bra straps down off of my shoulders and set loose my breasts without taking my bra off. He didn't even try to take my panties off, he just ripped them right off of my body. Luckily I wasn't wearing a good pair.
He half pushed, half threw me onto the seat of the couch. Without even saying a word, he kneeled between my legs and bit my breast. He did not bite enough to really hurt badly, but it did sting after he released it. He did the same with the other breast. He then went back to the first one and started to gnaw on it and lick it. This was not romantic at all. I was getting the feeling that I was something of a feast. After he finished the first one, with surprisingly no bruising, he went to the other one. My breasts were both so tender that they were in erotic pain. They were so sensitive that the air on them aroused them. That was not to say that other parts of my body were not reacting.
I was getting very wet between my legs. I felt the liquid build up inside of me. I think he knew it too. With a rough kiss on my lips, he descended down my stomach with his nails, put his head in between my legs, and started eating. I felt his nails slightly dig into me as he took his first bite of my tender sex flesh. I jumped from the intensity of his hunger of my body. I was speechless the entire time while he was manhandling me. He was careful but not gentle with me. My clit became elongated, and I let out a moan. He looked up from what he was doing with a feral smile. He was so wild that I couldn't keep my sounds of pleasure in anymore. His fingers went deep inside of me, his tongue and teeth worked on my clit. I was getting dizzy.
After that went on for a while, my body started to shutter from orgasms. He would not just let me orgasm once. He was torturing me with them. He went to greater strides for the next one. My throat was going hoarse from my moans, sighs, and then screams. The more noise I made, the more he dug into me. He reached up and grabbed my breast and squeezed it tight.
When I could scream no more and my throat was completely dry, he did give me a chance to calm down. I shook my head to clear it. I sat there for a few moments dazed by the onslaught. I took a deep breath and then a sip of my drink that I brought with me. I sat back to regain my composure. He was sitting on the floor, looking at me while he was refreshing himself as well. I couldn't tell what was going to come next, and I didn't want to. This totally unexpected side of him had me phased.
The respite was not long, but enough to gather my wits. I sat there and when I was about to open my mouth for a question, he stood up. He came over to and knelt in front of me. He put his hand on my butt and pulled it towards the edge of the seat. He then stood in front of me; it did not take me that long to figure out what he wanted. I placed my lips on his sex and started to kiss it gently. That would not do for him. He shoved it into my mouth. He did not move after that, but I got the hint. He wanted it fast. I did my best to please him, and when he put his hands on my shoulders, I knew that I was doing a good job of it.
I wrapped my lips around his shaft firmly and sucked on it. My tongue played over the tip of it, and my hand was ever so gently rubbing his balls. I took it out and my other hand started rubbing the tip of it, as I stood up. I was more gentle than he was, by just gently turning him around and making it known that I wanted him to sit.
When he was seated, I knelt between his legs.
I kissed and nipped at his neck and shoulders. I kissed down from there to his nipples. I licked his nipples and gently bit on them for several minutes. Each one, I could tell, were becoming more sensitive each time I bit or licked. My ministrations of his nipples were coupled with my light rubbing on the head of his sex. I lightly caressed it, smiling as I did, knowing that he loved it. He did not stay quiet for long. He moaned when I licked on his nipples. He tensed when my hand ran across the head of his sex. I then descended with kisses down his stomach to his shaft. I took it into my mouth once again. I did not let him have control of my slow ministrations. I wanted him to feel every lick. I wanted him to feel the suction in my mouth.
When he was near the breaking point, he shoved me away from him. I was confused for a moment. I had been lost in giving him pleasure. He towered over me. I was still kneeling, when he grabbed my by my elbows and made me sit on the couch. He pressed me backwards and lifted my legs. He then inserted himself into me. We nearly screamed in harmony.
Because of the intensity of the foreplay, neither of us was going to last long. We both knew it. After a few minutes, we were both spent and breathing heavily. He looked at me and smiled. I could not even think. He gently lifted me up off the couch and guided me upstairs to the bathroom. I don't think that I could have done that on my own. He offered to help me clean up, and I took that offer up. He gently washed my sex and wherever else his seed fell on my body.
After that, we went back downstairs and sat, naked, on the couch holding each other. I could not be more content. I smiled as I laid my head on his shoulder and felt as if everything in the world was right.
