#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib '../../files/lib';
use Base::Page qw(page story);

page( 'code' => sub { story(*DATA) });

__DATA__
The wind chimes tinkling together signal that she is near. The wind blows softly through the windows and the balcony door. A whirlwind is created out of the leaves that have settled on the balcony floor. Then she appears.
She wears little, only a mist-like dress. Her body is slender, almost perfect. Her eyes burn a blue fire, and one could drown in their blue depths. Her hair shines like the rays of the sun, casting out to help light the day. Her lips are like the petals of the reddest roses. They part in feigned innocence. She walks with the grace of and her body moves like a cat.
The material of her gown rustles against her pale, soft skin. Her body shows through her gown, though it is partially obscured.
She walks over to the man that she must seduce. The task was laid on her years ago.
He stares transfixed looking at this wonder of beauty. He does not know what to say or do. He does not know the meaning of her presence. He only knows that he now lusts for her with a fiery passion. He stands up, going over to this woman who has intruded in his home. He does not mind this for he is entranced.
He opens his mouth to speak. She silences him with a finger to his lips. His only attempt at communicating to her has been cut off.
She takes him to his bed. She starts to disrobe him, one piece of clothing at a time. She first takes off his shirt which is easily done for it is buttoned not a pull over. She then sits him down on the bed and removes his shoes then his socks. She motions for him to stand again. He stands in anticipation. She kisses his lips with her rosy red ones. She places her tongue into his mouth, playing it all over. It darts to his tongue and plays over the top of it. She runs her tongue on the roof of his mouth. She kisses his shoulder and nibbles a little on it. She kisses from his shoulder to his neck. She bites his neck lightly and then urgently but not to bring pain. She kisses up his neck to his ears. She playfully nibbles on his earlobe and then licks around it. She goes back down to his neck. She kisses around his neck to his other shoulder. She repeats her ministrations on the other side. Playfully nibbling on his other ear, she runs her warm hands down his chest and rubs his nipples between her fingers. She then kisses down his chest, takes one of his nipples into her mouth and sucks it while running her tongue around its edge. She places his nipple between her teeth and bites down on it to the point where she has it firmly secured and runs her tongue on the tip of his nipple. She hears his breath becomes ragged. She kisses her way to the other nipple, sucks on it, nibbles it, and licks it till it is hard as its counterpart.
Her hands trail down his body to his pants. She unbuttons the top button and then unzips them. She takes them off his hips, and they fall to the floor. She places her hands on his hips, under his underclothing, and forces them down to the floor. She motions him to step out of the clothes on the floor.
Using his pants as a cushion, she kneels down on the floor before him and kneads his penis with her hand. It starts to get hard. She kisses its tip and licks the tiny hole on its head. She licks around the ridge of the head of his penis. He is harder now. She takes the whole of his penis into her mouth. She sucks on it and runs her tongue on it until it is hard as a rock. She does not stop. She reaches around and takes hold of his butt-cheeks. She squeezes them lightly to help keep her balance.  She continues to run her tongue over his penis and around the ridge of its head. She again licks to tiny hole on the head. She then tastes his semen. She runs her tongue over the whole head. She moves her mouth to suck on his testicles. She sucks on them, giving him a whole new experience of pleasure. She hears him moan. She does not stop playing her mouth, tongue, and teeth over his most sensitive area of pleasure. She takes the whole of his penis into her mouth. She runs her lips up and down that shaft. She stops to lick to head of his penis once again and tastes another little drop of his fluid. She runs her tongue around the ridge of its head once more. She again takes his penis into her mouth. The she stops for a moment.
She looks at his face. It shows his pleasure at her ministrations. He is more aroused than he has ever been. She is aroused by giving this pleasure.
She makes him sit on the bed. She leans him back until he is prone. She mounts him with deliberate slowness. His face shows he is in a world of pleasure. She places his hands on her hips. She takes them up to her breasts and lets them take on a mind of their own. She becomes more aroused by this.
She moves her hips slowly forward, and them slowly back. She lifts her hips up, and then down. Her body moves faster and faster with each set of movements. He groans and bucks her trying to find the place of release. She does not let him have it yet. She stops and just sits there on him and rubs his already sensitive chest. She rubs his nipples and lightly pinches them. She does not let him move. Lightly pinching. Lightly rubbing. She leans forward and sucks and nibbles on his nipples. She still does not let him move to release. She slowly moves again.
He then releases into her body. He holds her hips. She moves his hand to her clitoris. She guides his hand, showing him how to pleasure her now. She is aroused and needs to release now too. She moves faster and faster on him.
She then releases herself. She climaxes and his penis feels the contractions. She relaxes then contracts over and over and over again.
He is spent and falls into a deep sleep. She slowly raises herself off of him and lies down next to him.
