#!/usr/bin/perl
use strict;
use warnings FATAL => qw( all );

use CGI::Carp qw(fatalsToBrowser);

use lib '../../files/lib';
use Base::Page qw(page story);

page( 'code' => sub { story(*DATA) });

__DATA__
Barbara lived alone and was fairly content with it. She has had boyfriends but none of the relationships lasted for long. The guys didn't understand her need for sexual toys to get her aroused. Most left when when her toys were used more than they were for sex.
One evening she looked at her inoperative vibrator with disdain but was so horny she used it as a dildo to relieve the ache she felt between her legs. This time was the last time she would get to use it, unfortunately, since it cracked when she knocked it against the sink while she was cleaning it.
In the silence of the night, several nights later, she tread through her apartment listening to the fabric of her dressing gown sliding on her skin. The lace of her bra tickled her nipples every time she moved which kept her horny for the whole evening. After finishing off a bottle of wine she opened a few nights before, she was a little drunk and a lot horny. Being toyless she thrust the empty bottle's neck deep inside her until she wasn't. A few days later, she was horny and toyless again; so she grabbed a fat handled spoon, covered the handle with plastic wrap, and fucked herself with it. In the middle of the evening two nights later, bored out of her mind, and wearing only shorts and panties; she sucked on her finger then stuck it right up inside of her vagina and wiggled it.
Over the next week, she didn't have the energy to masturbate. At work Barbara and her co-workers were moving file boxes to a new site. Near the end of the week, she was in so much pain she masturbated with just her fingers hoping to release more endorphins while waiting for the pain killers to kick in. It helped a little, but after her orgasm the pain returned.
Sitting naked on her bed because of the heat, she didn't know she gave her neighbor a ferocious hard on. Every night for the last month, Dirk watched her masturbating across the small street between their apartments while he washed his dishes. How did she know when he would be there? He took another look and saw her eyes closed, so she probably didn't know he was standing and watching. He saw her mouth open in what appeared to be a scream probably from an orgasm. Feeling a little guilty for his voyeurism over the last month, he got a piece of paper out of his printer and wrote her a little note which he taped on the window above his sink. As her masturbatory orgasms subsided, she looked out her window and saw the note across the way Q<Thanks for the show.>
In the middle of the next week when she got home, she took a shower before masturbating and going to sleep. She was naked and damp but could not find satisfaction alone any more. She looked out her bedroom window but didn't see her neighbor though she could see light from another room. She had never seen her neighbor, yet the idea of having sex with a person she's never met excited her more. She had been a little creeped out when she opened her eyes and saw the note, but since then she had not been able to orgasm from masturbation. She put on some things which resembled clothing and walked the bridge hallway to the apartment across from hers. She gently knocked on the door not expecting her neighbor to answer. Thinking about it now, she didn't even know if the neighbor was a man or a woman. The door opened slowly, and the man she saw in the doorway took her breath away.
Q<Can I help you?> he asked with a small smile on his face.
Q<I think you can, that is, if you want to?> she said with a slight tremor in her voice.
Q<You live across the way from me, and I think I can.> he said as he gestured Barbara to enter.
Barbara walked into Dirk's apartment and then into his living room. His apartment didn't have much in it, and all of the furniture was functional though nothing really matched. She then noticed the end table on the side of the sofa away from the door. He had a collection of things she had used as masturbatory toys in a basket with the exception of an opened full bottle of wine sitting next to the basket. He filled two glasses and handed one to her. After her first sip she had to ask, Q<How did you know?>
He smiled, Q<Over the last week, I've noticed you haven't completed one session. Yesterday, I decided to buy your favorite things. I've been building my courage up to come over to see you tomorrow. Then tonight I saw you start, then get dressed, I suspected you were coming here. At least I was hoping.>
When their first glasses of wine were empty, Barbara began to relax. After Dirk refilled both of their glasses, he lightly ran his finger down her shirt over the buttons then holding the bottom button between two fingers. She smiled and nodded to him, giving him permission to undo the buttons. When her shirt was unbuttoned, Barbara let it slide off of her shoulders and then she took it completely off, dropping it to the floor. She wasn't wearing a bra, so her breasts were completely exposed. She then leaned forward to unbutton his shirt, which he removed quickly.
Sitting on the small sofa, they drank their second glasses of wine bare chested. Since it was a small bottle of wine, Dirk topped off the glasses to empty it. It was a good bottle of wine having no labeling except on the bottle itself, nothing on the neck of it. When they were finished drinking; he placed the bottle on the coffee table, stood up moving in front of Barbara, holding his hands out for hers. She took his hands, and he helped her stand. He slowly put his hands on her sides under her arms and moved them down to the waistband of her pants. He looked into her eyes again questioning, and she wiggled her hips to indicate permission with a smile. He slid her loose pants off of her hips letting gravity take them down to the floor.
Dirk picked up the empty bottle and rubbed the mouth of it on her sparse pubic hair above Barbara's labia while she was still standing. She spread her legs a little, but he guided her back to sitting on the sofa. When she was seated, he sat next to her as she spread her legs again. This time he put the mouth of the bottle over her clit and rubbed it around her clit a few times before moving it downward. He placed the mouth of the bottle right inside the mouth of her vagina, holding it there for a full minute as he watched her face. With her eyes closed, she began to slide her hips down towards the bottle, but he stopped her with his other hand. He gently pushed the neck of the bottle inside of her until the neck of the bottle was fully inside of her. He then slowly pulled it almost completely out of her. He repeated the motion several times as she began to moan softly.
Smiling at making Barbara moan, Dirk removed the bottle from her completely and put it on the coffee table. She opened her eyes and looked at the bottle. She was going to say Q<Is that it?> when she saw him take a kitchen spoon with a very fat handle from the basket. The handle was covered with a condom, and he put lubricant on it. She smiled again as he rubbed the end of the spoon over her clit and vaginal opening. As slowly as he inserted the bottle, he inserted the handle of the spoon. She moaned as he pushed it inside of her. Also, as with the bottle, he only went a few very slow strokes with the spoon before removing it. He did the same with every item in the basket. Her moans became louder and longer with each new item from the basket. Her eyes stayed closed after the spoon, which is why she did not see the vibrator he took from the basket. He hid it under all the common household implements.
Dirk rubbed the tip of the vibrator all over the insides of Barbara's labia and over her clit. He swirled it gently at the mouth of her vagina. Since she had not opened her eyes, he smiled as he thrust it deep inside of her quickly. She gasped at the speed of the thrust. He then turned it on. The moment he turned it on, she was very close to screaming with pleasure. The vibrator had a clit extension which, when it touched hers, had her convulsing into her first orgasm in a week. Her eyes opened wide as he held it inside of her as she spasmed again and again. She could not stop her orgasms from rippling through her body.
As Barbara's orgasms began to subside, Dirk stood up smiling. As she looked him over, she noticed his penis almost aggressively pushing at the fabric of his pants. She lifted her hand towards it. He quickly unbuttoned and unzipped his pants and pushed them and his underwear to the floor. He stood in front of her fully naked, and she did not leave him untended long. She lightly rubbed the tip of his penis with her fingertips, then slowly wrapped her fingers around it. With just those touches, a small stream of clear cum appeared at the tip. She leaned forward and licked it away. His penis jumped a little in her hands, so she put the entire thing in her mouth. It pulsed several moments, when she removed it from her mouth, picked up the wine bottle, and caught his cum inside of the wine bottle.
When Dirk's orgasm stopped, he sat down on the sofa next to Barbara. Both of them had to regain some sort of composure.
Q<Would you care for something to eat?> Dirk asked after a quarter of an hour passed.
Q<That would be nice.> Barbara said with a smile.
Dirk got up and rummaged around his kitchen grabbing crackers and other snacks. He brought them to the living room where they nibbled on this and that in silence. Barbara looked at the clock to see only about an hour had passed. They were still naked when he pulled the lace lining out of the basket.
Q<There is one toy I have not used.> Dirk said as he held up with lace.
Q<And what are you going to do with it?> Barbara asked.
Q<This.> he said as he placed it over her breasts then rubbed it gently over them. She was still sensitive from the earlier play, but the time snacking renewed her and him. She started to feel horny again, so she leaned back on the sofa.
Q<Are you able to go again so soon?> Barbara asked with a smile.
Q<For you, yes I am.> Dirk replied as he leaned forward to kiss her.
The lace between them aroused the both of them once again. This time they did not use toys of any kind. His penis rubbed against her labia and clit, which made it harden again. He had the box of condoms behind the basket, so grabbed one quickly. She took it from him and slowly rolled it over his penis. When her fingers reached the bottom of his penis, she gently rubbed his testes. His penis jerked once more, showing how ready he was.
Leaning over Barbara, Dirk slowly inserted himself. She gasped again, still being sensitive from the earlier playing. When he was finally fully inside of her, they moaned together. With that Dirk could not control himself anymore. He pumped himself in and out of her fast and hard. Neither of them lasted long, meaning in a matter of minutes they were both orgasming again. These orgasms did not last as long as the first, but they were enough.
As they caught their breaths again, they looked into each other's eyes. Words failed them in the moment. Dirk collapsed beside Barbara on the sofa. Though she did not have to work the next day, she was feeling more than a little tired, so she began to organize herself to go home.
Q<Leaving me so soon?> Dirk asked still a little winded.
Q<Just for now. I am tired, and you look exhausted.> Barbara noted.
Q<You're right.>
Q<You could always bring the basket over to my place tomorrow night for an up close repeat performance.> she said as she pulling the shirt back on.
Q<Sounds like a date.>
Q<It is, and I'll get the wine.>
The next night Dirk showed up with the basket. They drank the wine and repeated the night before. Over time the toys in the basket started to gather dust as Barbara stopped needing them. Dirk became enough for her.